
-- Add structured dosage columns to drug_reference
ALTER TABLE public.drug_reference
ADD COLUMN IF NOT EXISTS dose_min_mg_kg numeric,
ADD COLUMN IF NOT EXISTS dose_max_mg_kg numeric,
ADD COLUMN IF NOT EXISTS route text,
ADD COLUMN IF NOT EXISTS frequency text,
ADD COLUMN IF NOT EXISTS concentration_mg_ml numeric;

-- Clear existing data and repopulate with comprehensive database
DELETE FROM public.drug_reference;

INSERT INTO public.drug_reference (name, commercial_name, active_ingredient, drug_class, species, indications, dosage, contraindications, adverse_effects, interactions, withdrawal_period, dose_min_mg_kg, dose_max_mg_kg, route, frequency, concentration_mg_ml) VALUES
-- AINEs
('Meloxicam', 'Maxicam, Flamavet', 'Meloxicam', 'AINE', 'Cães, Gatos', 'Analgesia, anti-inflamatório, antipirético. Dor musculoesquelética, pós-operatório, osteoartrite.', 'Cães: 0.1-0.2 mg/kg VO/SC SID. Gatos: 0.05-0.1 mg/kg VO/SC SID (máx 3 dias).', 'Insuficiência renal, hepática, gestação, desidratação, úlcera gastrointestinal.', 'Vômito, diarreia, ulceração GI, nefrotoxicidade, hepatotoxicidade.', 'Outros AINEs, corticosteroides, anticoagulantes, aminoglicosídeos, diuréticos.', 'Não se aplica', 0.1, 0.2, 'VO, SC', 'SID', 2),
('Carprofeno', 'Rimadyl, Carproflan', 'Carprofeno', 'AINE', 'Cães', 'Analgesia, anti-inflamatório pós-operatório, osteoartrite.', 'Cães: 2.2 mg/kg VO BID ou 4.4 mg/kg VO SID.', 'Gatos (não aprovado), insuficiência renal/hepática, gestação.', 'Vômito, diarreia, hepatotoxicidade, nefrotoxicidade.', 'Outros AINEs, corticosteroides, nefrotóxicos.', 'Não se aplica', 2.2, 4.4, 'VO', 'SID ou BID', 25),
('Firocoxibe', 'Previcox', 'Firocoxibe', 'AINE (COX-2 seletivo)', 'Cães', 'Osteoartrite, dor pós-operatória ortopédica e de tecidos moles.', 'Cães: 5 mg/kg VO SID.', 'Gatos, insuficiência renal/hepática, gestantes.', 'Vômito, diarreia, diminuição do apetite.', 'Outros AINEs, corticosteroides.', 'Não se aplica', 5, 5, 'VO', 'SID', NULL),
('Dipirona', 'Dipirona Vet, D-500', 'Dipirona sódica', 'Analgésico/Antipirético', 'Cães, Gatos, Equinos, Bovinos', 'Analgesia, antipirético. Dor leve a moderada, febre.', 'Cães/Gatos: 25 mg/kg VO/IV/IM BID-TID. Equinos: 20-25 mg/kg IV.', 'Hipersensibilidade, discrasias sanguíneas.', 'Hipotensão (IV rápida), agranulocitose (raro), reações alérgicas.', 'AINEs (risco aditivo GI).', 'Bovinos leite: 4 dias. Carne: 14 dias.', 25, 25, 'VO, IV, IM', 'BID a TID', 500),
('Cetoprofeno', 'Ketofen', 'Cetoprofeno', 'AINE', 'Cães, Gatos, Equinos', 'Anti-inflamatório, analgésico, antipirético.', 'Cães/Gatos: 1 mg/kg VO/SC/IM SID (máx 5 dias). Equinos: 2.2 mg/kg IV SID.', 'Insuficiência renal/hepática, úlcera GI, gestação.', 'Vômito, diarreia, ulceração GI.', 'Outros AINEs, corticosteroides, anticoagulantes.', 'Bovinos: 1 dia (leite), 4 dias (carne).', 1, 2.2, 'VO, SC, IM, IV', 'SID', 10),

-- Antibióticos
('Amoxicilina', 'Amoxil Vet, Agemoxi', 'Amoxicilina tri-hidratada', 'Antibiótico (Penicilina)', 'Cães, Gatos', 'Infecções bacterianas de pele, trato urinário, respiratório, otite.', 'Cães/Gatos: 10-20 mg/kg VO BID por 7-14 dias.', 'Hipersensibilidade a penicilinas/cefalosporinas.', 'Vômito, diarreia, reações alérgicas.', 'Methotrexato, anticoagulantes orais.', 'Não se aplica', 10, 20, 'VO', 'BID', 50),
('Amoxicilina + Clavulanato', 'Clavamox, Synulox', 'Amoxicilina + Ácido clavulânico', 'Antibiótico (Penicilina + Inibidor de β-lactamase)', 'Cães, Gatos', 'Infecções resistentes a amoxicilina, pioderma, ITU, pneumonia, abscessos.', 'Cães/Gatos: 12.5-25 mg/kg VO BID por 7-14 dias.', 'Hipersensibilidade a penicilinas.', 'Vômito, diarreia, hepatotoxicidade (raro).', 'Methotrexato, alopurinol.', 'Não se aplica', 12.5, 25, 'VO', 'BID', 50),
('Cefalexina', 'Rilexine, Celesporin', 'Cefalexina', 'Antibiótico (Cefalosporina 1ª geração)', 'Cães, Gatos', 'Pioderma, ITU, infecções ósseas, tecidos moles.', 'Cães/Gatos: 15-30 mg/kg VO BID por 7-28 dias (pioderma até 6 sem).', 'Hipersensibilidade a cefalosporinas/penicilinas.', 'Vômito, diarreia, alergia.', 'Aminoglicosídeos (nefrotoxicidade aditiva).', 'Não se aplica', 15, 30, 'VO', 'BID', 50),
('Enrofloxacina', 'Baytril', 'Enrofloxacina', 'Antibiótico (Fluoroquinolona)', 'Cães, Gatos (com restrições)', 'Infecções urinárias, respiratórias, cutâneas, otite.', 'Cães: 5-20 mg/kg VO/IM SID. Gatos: 5 mg/kg VO SID (não exceder).', 'Filhotes em crescimento (dano cartilagem), gatos (retinopatia em doses altas), gestantes.', 'Vômito, artropatia em jovens, retinopatia em gatos, cristalúria.', 'Teofilina, AINEs, antiácidos (reduzem absorção).', 'Bovinos: 12 dias carne, 3 dias leite.', 5, 20, 'VO, IM', 'SID', 50),
('Metronidazol', 'Flagyl Vet', 'Metronidazol', 'Antibiótico/Antiprotozoário', 'Cães, Gatos', 'Giardíase, infecções anaeróbias, doença inflamatória intestinal, colite.', 'Cães: 15-25 mg/kg VO BID. Gatos: 10-15 mg/kg VO BID. Por 5-7 dias.', 'Gestação, hepatopatia grave, neutropenia.', 'Neurotoxicidade (doses altas), vômito, anorexia, hepatotoxicidade.', 'Fenobarbital, warfarina, cimetidina.', 'Não se aplica', 10, 25, 'VO, IV', 'BID', 40),
('Doxiciclina', 'Doxitrat, Ronaxan', 'Doxiciclina', 'Antibiótico (Tetraciclina)', 'Cães, Gatos', 'Erliquiose, anaplasmose, hemoplasmose, leptospirose, infecções respiratórias.', 'Cães/Gatos: 5-10 mg/kg VO BID por 14-28 dias (hemoparasitas).', 'Gestação, filhotes <6 meses (manchas dentárias).', 'Vômito, esofagite (gatos), fotossensibilização.', 'Antiácidos, ferro, cálcio (reduzem absorção), fenobarbital.', 'Não se aplica', 5, 10, 'VO', 'BID', 20),
('Azitromicina', 'Zitromax Vet', 'Azitromicina', 'Antibiótico (Macrolídeo)', 'Cães, Gatos', 'Infecções respiratórias, cutâneas, bartonella, criptosporidiose.', 'Cães/Gatos: 5-10 mg/kg VO SID por 3-5 dias ou em dias alternados.', 'Hepatopatia grave.', 'Vômito, diarreia, anorexia.', 'Antiácidos, ciclosporina, digoxina.', 'Não se aplica', 5, 10, 'VO', 'SID', 40),
('Ceftriaxona', 'Triaxon Vet', 'Ceftriaxona', 'Antibiótico (Cefalosporina 3ª geração)', 'Cães, Gatos', 'Infecções graves, sepse, meningite, pneumonia grave.', 'Cães/Gatos: 25-50 mg/kg IV/IM SID-BID.', 'Hipersensibilidade a cefalosporinas.', 'Dor no local IM, diarreia, nefrotoxicidade.', 'Aminoglicosídeos, diuréticos de alça.', 'Não se aplica', 25, 50, 'IV, IM', 'SID a BID', 100),
('Sulfametoxazol + Trimetoprima', 'Bactrim Vet, Tribrissen', 'Sulfametoxazol + Trimetoprima', 'Antibiótico (Sulfonamida)', 'Cães, Gatos', 'ITU, prostatite, infecções GI, coccidiose, toxoplasmose.', 'Cães/Gatos: 15-30 mg/kg VO BID por 7-21 dias.', 'Insuficiência hepática/renal, anemias, deficiência de folato, Doberman (risco imunomediado).', 'Ceratoconjuntivite seca, hepatotoxicidade, anemia, cristalúria.', 'Pirimetamina, metotrexato, anticoagulantes.', 'Não se aplica', 15, 30, 'VO', 'BID', NULL),

-- Antiparasitários
('Sarolaner', 'Simparic', 'Sarolaner', 'Antiparasitário (Isoxazolina)', 'Cães', 'Pulgas, carrapatos, sarnas (demodécica e sarcóptica).', 'Cães: 2-4 mg/kg VO dose única mensal.', 'Gatos (não aprovado), filhotes <8 semanas ou <1.3 kg, epilépticos.', 'Vômito, diarreia, tremores (raro).', 'Sem interações significativas conhecidas.', 'Não se aplica', 2, 4, 'VO', 'Mensal', NULL),
('Afoxolaner', 'NexGard', 'Afoxolaner', 'Antiparasitário (Isoxazolina)', 'Cães', 'Pulgas e carrapatos.', 'Cães: 2.5-6.2 mg/kg VO dose única mensal.', 'Gatos, filhotes <8 semanas ou <2 kg, epilépticos.', 'Vômito, diarreia, letargia.', 'Sem interações significativas conhecidas.', 'Não se aplica', 2.5, 6.2, 'VO', 'Mensal', NULL),
('Fluralaner', 'Bravecto', 'Fluralaner', 'Antiparasitário (Isoxazolina)', 'Cães, Gatos', 'Pulgas e carrapatos (cães). Pulgas (gatos spot-on).', 'Cães: 25-56 mg/kg VO dose única a cada 12 semanas. Gatos: tópico.', 'Filhotes <8 semanas ou <2 kg, epilépticos.', 'Vômito, diarreia, redução apetite.', 'Sem interações significativas conhecidas.', 'Não se aplica', 25, 56, 'VO', 'A cada 12 semanas', NULL),
('Ivermectina', 'Ivomec', 'Ivermectina', 'Antiparasitário (Avermectina)', 'Cães, Gatos, Bovinos, Equinos, Ovinos', 'Sarna demodécica, sarcóptica, nematódeos, microfilárias.', 'Cães: 0.2-0.4 mg/kg VO/SC. Sarna demodécica: 0.3-0.6 mg/kg VO SID. Bovinos: 0.2 mg/kg SC.', 'Raças sensíveis (Collie, Pastor de Shetland, Bobtail — mutação MDR1). Não usar em filhotes <6 semanas.', 'Midríase, ataxia, tremores, coma (intoxicação), sialorreia.', 'Spinosade, milbemicina (risco aditivo MDR1).', 'Bovinos carne: 35 dias. Leite: 28 dias.', 0.2, 0.6, 'VO, SC', 'SID ou dose única', 10),
('Milbemicina oxima', 'Milbemax, Interceptor', 'Milbemicina oxima', 'Antiparasitário (Milbemicina)', 'Cães, Gatos', 'Prevenção de dirofilariose, nematódeos GI, sarna demodécica.', 'Cães: 0.5-1 mg/kg VO. Prevenção dirofilária: mensal.', 'Filhotes <2 semanas, raças MDR1 sensíveis (dose demodécica).', 'Vômito, letargia, ataxia (raro).', 'Ivermectina (efeito aditivo).', 'Não se aplica', 0.5, 1, 'VO', 'Mensal', NULL),
('Praziquantel', 'Drontal, Vermivet', 'Praziquantel', 'Anti-helmíntico (Cestodicida)', 'Cães, Gatos', 'Cestóides (Dipylidium, Taenia, Echinococcus).', 'Cães/Gatos: 5 mg/kg VO dose única.', 'Filhotes <4 semanas.', 'Vômito, diarreia, salivação, letargia transitória.', 'Sem interações significativas.', 'Não se aplica', 5, 5, 'VO', 'Dose única', 50),

-- Corticosteroides
('Prednisolona', 'Prediderm, Meticorten Vet', 'Prednisolona', 'Corticosteroide', 'Cães, Gatos', 'Anti-inflamatório, imunossupressor. Doenças autoimunes, alergias, asma felina.', 'Anti-inflamatório: 0.5-1 mg/kg VO SID. Imunossupressão: 2-4 mg/kg VO SID.', 'Diabetes, infecções fúngicas sistêmicas, úlcera GI.', 'PU/PD/PP, diabetes iatrogênico, hiperadrenocorticismo, ulceração GI, imunossupressão.', 'AINEs (risco GI), insulina, vacinas vivas.', 'Não se aplica', 0.5, 4, 'VO', 'SID a BID', 5),
('Dexametasona', 'Azium, Cortvet', 'Dexametasona', 'Corticosteroide', 'Cães, Gatos, Equinos', 'Anti-inflamatório potente, edema cerebral, choque, alergias graves.', 'Anti-inflamatório: 0.05-0.2 mg/kg IV/IM/VO SID. Choque: 2-4 mg/kg IV.', 'Diabetes, infecções fúngicas, gestação.', 'PU/PD/PP, imunossupressão, atrofia muscular, laminite (equinos).', 'AINEs, insulina, diuréticos, anfotericina B.', 'Bovinos leite: 3 dias. Carne: 8 dias.', 0.05, 0.2, 'IV, IM, VO', 'SID', 2),

-- Anestésicos e Sedativos
('Cetamina', 'Ketalar Vet, Vetanarcol', 'Cetamina', 'Anestésico dissociativo', 'Cães, Gatos, Equinos', 'Indução anestésica, sedação, analgesia somática.', 'Cães: 5-10 mg/kg IV (com diazepam). Gatos: 10-20 mg/kg IM.', 'Cardiopatia hipertrófica, hipertensão, trauma craniano (eleva PIC).', 'Taquicardia, hipertensão, hipertonia, recuperação agitada.', 'Diazepam/midazolam (combinação sinérgica), xilazina, medetomidina.', 'Não se aplica', 5, 20, 'IV, IM', 'Dose única', 100),
('Propofol', 'Propovan, Diprivan Vet', 'Propofol', 'Anestésico injetável', 'Cães, Gatos', 'Indução e manutenção anestésica, procedimentos curtos.', 'Cães/Gatos: 4-6 mg/kg IV lento (até efeito). Manutenção: 0.2-0.4 mg/kg/min.', 'Hipovolemia não corrigida, sem acesso venoso, uso repetido em gatos (corpúsculos Heinz).', 'Apneia, hipotensão, bradicardia.', 'Opioides (reduz dose), benzodiazepínicos, alfa-2 agonistas.', 'Não se aplica', 4, 6, 'IV', 'Dose única', 10),
('Xilazina', 'Anasedan, Rompun', 'Xilazina', 'Sedativo/Analgésico (α2-agonista)', 'Cães, Gatos, Equinos', 'Sedação, pré-anestésico, analgesia visceral.', 'Cães: 0.5-1 mg/kg IV/IM. Gatos: 0.5-1 mg/kg IM. Equinos: 0.5-1.1 mg/kg IV.', 'Cardiopatia, arritmias, obstrução uretral, gestação, debilitados.', 'Bradicardia, hipotensão, vômito, depressão respiratória, hiperglicemia.', 'Outros depressores do SNC, epinefrina (arritmia).', 'Bovinos leite: 1 dia. Carne: 3 dias.', 0.5, 1.1, 'IV, IM', 'Dose única', 20),
('Medetomidina', 'Domitor', 'Medetomidina', 'Sedativo/Analgésico (α2-agonista)', 'Cães, Gatos', 'Sedação, pré-anestésico, contenção química.', 'Cães: 10-40 µg/kg IV/IM. Gatos: 40-80 µg/kg IM.', 'Cardiopatia, hepatopatia, nefropatia, gestação.', 'Bradicardia, hipertensão transitória, vômito, depressão respiratória.', 'Outros sedativos, opioides (efeito aditivo). Reversão: atipamezol.', 'Não se aplica', 0.01, 0.08, 'IV, IM', 'Dose única', 1),

-- Opioides
('Tramadol', 'Tramadol Vet, Cronidor', 'Tramadol', 'Opioide atípico', 'Cães, Gatos', 'Analgesia moderada a intensa, dor crônica, pós-operatório.', 'Cães: 2-5 mg/kg VO BID-TID. Gatos: 1-2 mg/kg VO BID.', 'Epilépticos, uso com IMAO, insuficiência hepática grave.', 'Sedação, náusea, constipação, disforia (gatos).', 'IMAO, ISRS (risco síndrome serotonérgica), fenobarbital.', 'Não se aplica', 1, 5, 'VO', 'BID a TID', 50),
('Morfina', 'Dimorf Vet', 'Morfina', 'Opioide (agonista µ)', 'Cães, Gatos', 'Analgesia intensa, dor pós-operatória, trauma.', 'Cães: 0.3-1 mg/kg IM/SC a cada 4-6h. Gatos: 0.1-0.3 mg/kg IM/SC.', 'Trauma craniano (eleva PIC), insuficiência respiratória.', 'Sedação, bradicardia, vômito, depressão respiratória, retenção urinária.', 'Outros depressores do SNC, IMAO.', 'Não se aplica', 0.1, 1, 'IM, SC', 'A cada 4-6h', 10),
('Metadona', 'Mytedom', 'Metadona', 'Opioide (agonista µ)', 'Cães, Gatos', 'Analgesia peri-operatória, dor moderada a intensa.', 'Cães: 0.2-0.5 mg/kg IV/IM a cada 4-6h. Gatos: 0.1-0.3 mg/kg IV/IM.', 'Depressão respiratória, trauma craniano.', 'Sedação, bradicardia, depressão respiratória.', 'Outros depressores SNC, IMAO.', 'Não se aplica', 0.1, 0.5, 'IV, IM', 'A cada 4-6h', 10),

-- Antieméticos
('Maropitant', 'Cerenia', 'Maropitant', 'Antiemético (antagonista NK1)', 'Cães, Gatos', 'Náusea, vômito agudo/crônico, cinetose.', 'Cães/Gatos: 1 mg/kg SC SID ou 2 mg/kg VO SID. Cinetose: 8 mg/kg VO.', 'Hipersensibilidade, filhotes <8 semanas.', 'Dor no local SC, letargia, diarreia.', 'Sem interações clínicas significativas.', 'Não se aplica', 1, 2, 'SC, VO', 'SID', 10),
('Ondansetrona', 'Vonau Vet', 'Ondansetrona', 'Antiemético (antagonista 5-HT3)', 'Cães, Gatos', 'Vômito quimioterápico, náusea refratária.', 'Cães/Gatos: 0.5-1 mg/kg IV/VO BID-TID.', 'Hipersensibilidade.', 'Constipação, cefaleia.', 'Tramadol (pode reduzir analgesia), apomorfina.', 'Não se aplica', 0.5, 1, 'IV, VO', 'BID a TID', 2),
('Metoclopramida', 'Plasil Vet', 'Metoclopramida', 'Pró-cinético/Antiemético', 'Cães, Gatos', 'Refluxo gastroesofágico, gastroparesia, vômito.', 'Cães/Gatos: 0.2-0.5 mg/kg VO/SC/IV TID ou 1-2 mg/kg/dia infusão contínua.', 'Obstrução GI, feocromocitoma, epilepsia.', 'Agitação, efeitos extrapiramidais (raro).', 'Opioides (efeito antagônico na motilidade), fenotiazínicos.', 'Não se aplica', 0.2, 0.5, 'VO, SC, IV', 'TID', 5),

-- Gastroprotetores
('Omeprazol', 'Gaviz, Petprazol', 'Omeprazol', 'Inibidor de bomba de prótons', 'Cães, Gatos', 'Úlcera gástrica/duodenal, esofagite, gastrite erosiva, prevenção AINE.', 'Cães/Gatos: 0.7-1 mg/kg VO SID-BID.', 'Hipersensibilidade.', 'Diarreia (raro).', 'Reduz absorção de cetoconazol, aumenta absorção de digoxina.', 'Não se aplica', 0.7, 1, 'VO', 'SID a BID', 10),
('Sucralfato', 'Sucrafilm', 'Sucralfato', 'Protetor de mucosa gástrica', 'Cães, Gatos', 'Úlcera gástrica, esofagite, gastrite.', 'Cães: 0.5-1 g VO TID-QID. Gatos: 0.25-0.5 g VO BID-TID. Dar em jejum.', 'Hipersensibilidade.', 'Constipação (alumínio).', 'Reduz absorção de fluoroquinolonas, tetraciclinas, digoxina. Dar separado 2h.', 'Não se aplica', NULL, NULL, 'VO', 'BID a QID', NULL),
('Ranitidina', 'Antak Vet', 'Ranitidina', 'Antagonista H2', 'Cães, Gatos', 'Gastrite, úlcera, esofagite, pró-cinético leve.', 'Cães: 2 mg/kg VO/IV BID-TID. Gatos: 2.5 mg/kg IV BID ou 3.5 mg/kg VO BID.', 'Hipersensibilidade.', 'Arritmia (IV rápida), vômito.', 'Cetoconazol (reduz absorção), metoclopramida (efeito sinérgico).', 'Não se aplica', 2, 3.5, 'VO, IV', 'BID a TID', 25),

-- Cardíacos
('Pimobendan', 'Vetmedin', 'Pimobendan', 'Inotrópico/Vasodilatador (Inodilatador)', 'Cães', 'Insuficiência cardíaca congestiva (DMVM, CMD). Estágio B2-D.', 'Cães: 0.25-0.3 mg/kg VO BID (em jejum, 1h antes da alimentação).', 'Estenose aórtica/subaórtica, cardiomiopatia hipertrófica.', 'Anorexia, diarreia, letargia (raros).', 'Outros inotrópicos, verapamil, diltiazem.', 'Não se aplica', 0.25, 0.3, 'VO', 'BID', NULL),
('Enalapril', 'Renitec Vet, Enacard', 'Enalapril', 'IECA', 'Cães, Gatos', 'Insuficiência cardíaca, hipertensão, proteinúria.', 'Cães: 0.5 mg/kg VO SID-BID. Gatos: 0.25-0.5 mg/kg VO SID-BID.', 'Estenose renal bilateral, hipotensão, hipercalemia.', 'Hipotensão, azotemia, hipercalemia.', 'Diuréticos poupadores de potássio, AINEs (reduz eficácia), potássio.', 'Não se aplica', 0.25, 0.5, 'VO', 'SID a BID', 5),
('Furosemida', 'Lasix', 'Furosemida', 'Diurético de alça', 'Cães, Gatos', 'Edema pulmonar, ICC, efusão pleural, ascite.', 'Cães: 1-4 mg/kg VO/IV/IM BID-TID. Gatos: 1-2 mg/kg VO/IV BID.', 'Desidratação, anúria, hipocalemia grave.', 'Desidratação, hipocalemia, hiponatremia, alcalose metabólica, ototoxicidade.', 'Aminoglicosídeos (ototoxicidade), digoxina (hipocalemia), IECA (hipotensão).', 'Não se aplica', 1, 4, 'VO, IV, IM', 'BID a TID', 10),
('Espironolactona', 'Aldactone', 'Espironolactona', 'Diurético poupador de potássio', 'Cães, Gatos', 'ICC (adjunto), controle de aldosterona, remodelamento cardíaco.', 'Cães: 1-2 mg/kg VO SID-BID. Gatos: 1-2 mg/kg VO SID.', 'Hipercalemia, insuficiência renal grave.', 'Hipercalemia, distúrbios GI.', 'IECA (hipercalemia aditiva), digoxina.', 'Não se aplica', 1, 2, 'VO', 'SID a BID', NULL),

-- Anticonvulsivantes
('Fenobarbital', 'Gardenal Vet', 'Fenobarbital', 'Anticonvulsivante (Barbitúrico)', 'Cães, Gatos', 'Epilepsia idiopática, convulsões recorrentes.', 'Cães: 2.5-5 mg/kg VO BID. Gatos: 1-2 mg/kg VO BID. Ajustar por nível sérico.', 'Hepatopatia grave, anemia grave.', 'Sedação, PU/PD/PP, hepatotoxicidade, ataxia.', 'Outros depressores SNC, cloranfenicol (eleva nível), cimetidina.', 'Não se aplica', 1, 5, 'VO', 'BID', 40),
('Diazepam', 'Valium Vet', 'Diazepam', 'Benzodiazepínico', 'Cães, Gatos', 'Status epilepticus, sedação, ansiolítico, miorrelaxante, estimulante de apetite (gatos).', 'Cães: 0.5-2 mg/kg IV (status epilepticus). Gatos: 0.2-0.5 mg/kg IV. Apetite gatos: 0.05-0.15 mg/kg IV.', 'Hepatopatia (gatos — risco necrose hepática fulminante VO), glaucoma de ângulo fechado.', 'Sedação, ataxia, hepatotoxicidade aguda em gatos (VO), paradoxal excitação.', 'Outros depressores SNC, cetamina (combinação sinérgica).', 'Não se aplica', 0.2, 2, 'IV', 'Dose única ou PRN', 5),

-- Dermatológicos e Antifúngicos
('Cetoconazol', 'Nizoral Vet', 'Cetoconazol', 'Antifúngico (Azol)', 'Cães', 'Dermatofitose, malassezia, blastomicose, hiperadrenocorticismo (off-label).', 'Cães: 5-10 mg/kg VO SID-BID por 4-8 semanas. Hiperadrenocorticismo: 10-15 mg/kg VO BID.', 'Hepatopatia, gestação, gatos (hepatotoxicidade elevada).', 'Hepatotoxicidade, vômito, anorexia, trombocitopenia.', 'Ciclosporina, ivermectina (eleva níveis), antiácidos (reduz absorção).', 'Não se aplica', 5, 15, 'VO', 'SID a BID', NULL),
('Itraconazol', 'Sporanox Vet, Itrafungol', 'Itraconazol', 'Antifúngico (Triazol)', 'Cães, Gatos', 'Dermatofitose, esporotricose, criptococose, aspergilose.', 'Cães/Gatos: 5-10 mg/kg VO SID ou em semanas alternadas.', 'Hepatopatia grave, gestação.', 'Hepatotoxicidade, anorexia, vômito.', 'Ciclosporina, midazolam, vincristina (eleva níveis).', 'Não se aplica', 5, 10, 'VO', 'SID', 10),
('Ciclosporina', 'Atopica', 'Ciclosporina', 'Imunossupressor', 'Cães, Gatos', 'Dermatite atópica, doença inflamatória intestinal, fístula perianal.', 'Cães: 5 mg/kg VO SID. Gatos: 7 mg/kg VO SID.', 'Neoplasias, infecções ativas, vacinação com vivas.', 'Vômito, diarreia, hiperplasia gengival, papilomas.', 'Cetoconazol (eleva nível — pode ser intencional para reduzir custo), AINE.', 'Não se aplica', 5, 7, 'VO', 'SID', 100),

-- Antihistamínicos
('Difenidramina', 'Difenidrin', 'Difenidramina', 'Anti-histamínico H1 (1ª geração)', 'Cães, Gatos', 'Reações alérgicas, prurido, pré-medicação transfusão.', 'Cães: 2-4 mg/kg VO/IM BID-TID. Gatos: 1-2 mg/kg VO/IM BID.', 'Glaucoma, retenção urinária.', 'Sedação, boca seca, retenção urinária.', 'Outros depressores SNC, IMAO.', 'Não se aplica', 1, 4, 'VO, IM', 'BID a TID', 10),

-- Endócrinos
('Insulina NPH', 'Humulin N, Caninsulin', 'Insulina NPH', 'Hormônio (Insulina de ação intermediária)', 'Cães, Gatos', 'Diabetes mellitus.', 'Cães: 0.25-0.5 UI/kg SC BID. Gatos: 0.25-0.5 UI/kg SC BID. Ajustar por curva glicêmica.', 'Hipoglicemia, insulinoma.', 'Hipoglicemia, lipodistrofia no local.', 'Corticosteroides (hiperglicemia), propranolol (mascara sinais de hipoglicemia).', 'Não se aplica', NULL, NULL, 'SC', 'BID', NULL),
('Levotiroxina', 'Synthroid Vet, Euthyrox', 'Levotiroxina sódica', 'Hormônio tireoidiano', 'Cães', 'Hipotireoidismo.', 'Cães: 0.02 mg/kg (20 µg/kg) VO BID. Ajustar por T4 pós-dose.', 'Tireotoxicose, insuficiência adrenal não tratada, cardiopatia descompensada.', 'Taquicardia, poliúria, perda de peso, agitação (sobredose).', 'Antiácidos (reduzem absorção), insulina (ajustar dose).', 'Não se aplica', 0.02, 0.02, 'VO', 'BID', NULL),
('Metimazol', 'Tapazol', 'Metimazol', 'Antitireoidiano', 'Gatos', 'Hipertireoidismo felino.', 'Gatos: 1.25-2.5 mg VO BID (iniciar baixo). Ajustar por T4 a cada 2-4 semanas.', 'Hepatopatia grave, mielossupressão.', 'Vômito, anorexia, letargia, escoriações faciais, hepatotoxicidade, mielossupressão.', 'Anticoagulantes, digoxina (ajustar ao normalizar T4).', 'Não se aplica', NULL, NULL, 'VO', 'BID', NULL),

-- Mucolíticos e Respiratórios  
('Acetilcisteína', 'Fluimucil Vet', 'Acetilcisteína', 'Mucolítico/Antídoto', 'Cães, Gatos', 'Mucolítico respiratório, antídoto para intoxicação por paracetamol.', 'Mucolítico: 10-20 mg/kg VO BID-TID ou nebulização. Antídoto: 140 mg/kg VO/IV (dose de ataque), depois 70 mg/kg a cada 6h (total 7 doses).', 'Asma aguda grave.', 'Náusea, vômito, broncoespasmo (inalação).', 'Sem interações significativas.', 'Não se aplica', 10, 20, 'VO, IV, Nebulização', 'BID a TID', 40),

-- Laxantes
('Lactulose', 'Lactulona', 'Lactulose', 'Laxante osmótico', 'Cães, Gatos', 'Constipação, megacólon, encefalopatia hepática.', 'Cães: 0.5-1 mL/kg VO BID-TID. Gatos: 0.5 mL/kg VO BID-TID.', 'Obstrução intestinal.', 'Flatulência, cólica, diarreia (dose excessiva).', 'Antiácidos (reduzem eficácia na encefalopatia).', 'Não se aplica', NULL, NULL, 'VO', 'BID a TID', NULL),

-- Anestésicos locais
('Lidocaína', 'Xylestesin, Lidovet', 'Lidocaína', 'Anestésico local / Antiarrítmico', 'Cães, Gatos', 'Anestesia local/regional, bloqueio nervoso, antiarrítmico (taquicardia ventricular).', 'Anestesia local: 2-4 mg/kg (não exceder 6 mg/kg em cães, 4 mg/kg em gatos). Antiarrítmico: 2 mg/kg IV bolus, seguido de infusão 40-80 µg/kg/min.', 'Bloqueio AV, bradicardia grave, hepatopatia grave, gatos (mais sensíveis).', 'Tremores, convulsões, bradicardia, hipotensão (doses altas).', 'Outros antiarrítmicos, betabloqueadores, cimetidina.', 'Não se aplica', 2, 6, 'SC, IV, Tópica', 'Conforme necessidade', 20),

-- Outros
('Carvão ativado', 'Carbovac', 'Carvão ativado', 'Adsorvente', 'Cães, Gatos', 'Intoxicações agudas (administrar até 2h após ingestão do tóxico).', 'Cães/Gatos: 1-2 g/kg VO (suspensão aquosa). Pode repetir a cada 4-6h.', 'Ingestão de cáusticos, obstrução GI, paciente inconsciente.', 'Vômito, constipação, fezes pretas (normal).', 'Adsorve outros medicamentos orais (separar 2h).', 'Não se aplica', NULL, NULL, 'VO', 'Dose única ou repetida a cada 4-6h', NULL),
('Atropina', 'Atropion', 'Sulfato de atropina', 'Anticolinérgico', 'Cães, Gatos', 'Bradicardia, pré-anestésico, intoxicação por organofosforados, broncoespasmo.', 'Cães/Gatos: 0.02-0.04 mg/kg IV/IM/SC. Organofosforados: 0.2 mg/kg IV (1/4 da dose), resto IM.', 'Taquicardia, glaucoma, íleo paralítico.', 'Taquicardia, midríase, boca seca, retenção urinária, íleo.', 'Anticolinérgicos aditivos, antagoniza metoclopramida.', 'Não se aplica', 0.02, 0.04, 'IV, IM, SC', 'Dose única', 0.5),
('Vitamina K1', 'Kanakion Vet', 'Fitomenadiona (Vitamina K1)', 'Antídoto / Vitamina', 'Cães, Gatos', 'Intoxicação por anticoagulantes (rodenticidas), coagulopatias.', 'Cães/Gatos: 2.5-5 mg/kg VO/SC BID. Tratar por 4-6 semanas (rodenticidas de 2ª geração).', 'Hipersensibilidade (IV pode causar anafilaxia). NUNCA usar IV.', 'Dor no local SC, hematoma.', 'Warfarina (antagônico), cefalosporinas (interferem metabolismo vit K).', 'Não se aplica', 2.5, 5, 'VO, SC', 'BID', NULL);
