-- Bulk insert of veterinary drugs into drug_reference
-- Skips existing entries by name to avoid duplicates

INSERT INTO public.drug_reference (name, active_ingredient, drug_class, species, indications, dosage, contraindications, adverse_effects, route, frequency, dose_min_mg_kg, dose_max_mg_kg)
SELECT v.name, v.active_ingredient, v.drug_class, v.species, v.indications, v.dosage, v.contraindications, v.adverse_effects, v.route, v.frequency, v.dose_min, v.dose_max
FROM (VALUES
-- === ANTIBIÓTICOS - BETALACTÂMICOS ===
('Amoxicilina','Amoxicilina triidratada','Antibiótico - Betalactâmico','Cães, Gatos, Bovinos, Equinos','Infecções bacterianas por gram-positivos e gram-negativos sensíveis; pele, trato respiratório, urinário e gastrointestinal','Cães/Gatos: 10–20 mg/kg a cada 8–12h VO; Bovinos: 7 mg/kg IM/SC 1x/dia','Hipersensibilidade a penicilinas ou cefalosporinas','Reações alérgicas, vômito, diarreia','Oral, IM, SC','A cada 8–12h',10,20),
('Amoxicilina + Clavulanato','Amoxicilina triidratada + Ácido clavulânico','Antibiótico - Betalactâmico + Inibidor beta-lactamase','Cães, Gatos','Infecções por bactérias produtoras de beta-lactamase; pele, trato respiratório, urinário e ossos','Cães/Gatos: 12,5–25 mg/kg a cada 12h VO','Hipersensibilidade a penicilinas','Vômito, diarreia, anorexia','Oral, IM','A cada 12h',12.5,25),
('Ampicilina','Ampicilina','Antibiótico - Betalactâmico','Cães, Gatos, Bovinos, Equinos, Aves','Infecções por gram-positivos e gram-negativos; septicemia, meningite, trato respiratório e urinário','Cães/Gatos: 10–22 mg/kg a cada 6–8h VO/IM/IV; Bovinos: 4–10 mg/kg IM 1x/dia','Hipersensibilidade a penicilinas','Reações alérgicas, diarreia','Oral, IM, IV, SC','A cada 6–8h',10,22),
('Cefalexina','Cefalexina monoidratada','Antibiótico - Cefalosporina 1ª geração','Cães, Gatos','Infecções de pele (piodermite), trato urinário, ossos e articulações','Cães/Gatos: 15–30 mg/kg a cada 8–12h VO','Hipersensibilidade a cefalosporinas ou penicilinas','Vômito, diarreia, salivação excessiva (gatos)','Oral','A cada 8–12h',15,30),
('Cefazolina','Cefazolina sódica','Antibiótico - Cefalosporina 1ª geração','Cães, Gatos','Profilaxia cirúrgica, infecções de pele, trato respiratório e urinário; gram-positivos','Cães/Gatos: 20–35 mg/kg IV/IM a cada 6–8h; profilaxia: 22 mg/kg IV pré-cirurgia','Hipersensibilidade a cefalosporinas','Reações alérgicas, dor no local de aplicação','IV, IM','A cada 6–8h',20,35),
('Cefovecina Sódica','Cefovecina sódica','Antibiótico - Cefalosporina 3ª geração','Cães, Gatos','Infecções de pele e tecidos moles; aplicação única com ação prolongada','Dose única SC: 8 mg/kg (cobre 7–14 dias)','Hipersensibilidade a cefalosporinas; não usar em filhotes <12 semanas','Vômito, diarreia, letargia','SC','Dose única',8,8),
('Cefpodoxima Proxetil','Cefpodoxima proxetil','Antibiótico - Cefalosporina 3ª geração','Cães, Gatos','Infecções de pele e tecidos moles, trato urinário, trato respiratório','Cães: 5–10 mg/kg a cada 24h VO; Gatos: 5 mg/kg a cada 12h VO','Hipersensibilidade a cefalosporinas','Vômito, diarreia','Oral','A cada 12–24h',5,10),
('Cloxacilina','Cloxacilina sódica','Antibiótico - Betalactâmico (isoxazolilpenicilina)','Cães, Gatos, Bovinos','Infecções por Staphylococcus spp. produtores de penicilinase; mastite bovina','Cães/Gatos: 20–40 mg/kg a cada 8h VO; mastite intramammária bovina: por bísnagas','Hipersensibilidade a penicilinas','Reações alérgicas, distúrbios GI','Oral, intramammária','A cada 8h',20,40),
-- === ANTIBIÓTICOS - QUINOLONAS ===
('Enrofloxacina','Enrofloxacina','Antibiótico - Fluoroquinolona','Cães, Gatos, Aves, Bovinos, Equinos, Répteis','Infecções por gram-negativos e Mycoplasma; trato urinário, respiratório, pele','Cães: 5–20 mg/kg/dia VO/IM/SC/IV; Gatos: 5 mg/kg/dia; Aves: 10–15 mg/kg a cada 12h VO','Filhotes em crescimento (dano articular); animais gestantes; insuficiência renal grave','Vômito, diarreia, retinopatia em gatos (doses altas), artropatia em jovens','Oral, IM, SC, IV','A cada 12–24h',5,20),
('Marbofloxacina','Marbofloxacina','Antibiótico - Fluoroquinolona','Cães, Gatos','Infecções de pele e tecidos moles, trato urinário e respiratório por gram-negativos','Cães/Gatos: 2,75–5,5 mg/kg/dia VO','Filhotes em crescimento, animais gestantes','Vômito, diarreia, diminuição do apetite','Oral','A cada 24h',2.75,5.5),
('Pradofloxacina','Pradofloxacina','Antibiótico - Fluoroquinolona 4ª geração','Cães, Gatos','Infecções de pele, trato urinário, respiratório e abscessos por gram-positivos e negativos','Cães: 3 mg/kg/dia VO; Gatos: 5 mg/kg/dia VO (comprimidos e suspensão)','Filhotes em crescimento, gestação, gatos com doença renal grave','Vômito, diarreia, náusea','Oral','A cada 24h',3,5),
('Ciprofloxacina','Ciprofloxacina cloridrato','Antibiótico - Fluoroquinolona','Cães, Gatos, Aves, Répteis','Infecções por gram-negativos; alternativa humana usada off-label em pequenos animais','Cães: 5–15 mg/kg a cada 12h VO; Gatos: 5–10 mg/kg a cada 12–24h','Filhotes em crescimento, gestação','Vômito, diarreia, artropatia em jovens','Oral, IV','A cada 12h',5,15),
('Orbifloxacina','Orbifloxacina','Antibiótico - Fluoroquinolona','Cães, Gatos','Infecções de pele, trato urinário e respiratório','Cães/Gatos: 2,5–7,5 mg/kg/dia VO','Filhotes em crescimento, gestação','Vômito, diarreia','Oral','A cada 24h',2.5,7.5),
-- === ANTIBIÓTICOS - TETRACICLINAS ===
('Doxiciclina','Doxiciclina cloridrato','Antibiótico - Tetraciclina','Cães, Gatos, Aves, Equinos','Erliquiose, anaplasmose, rickettsia, Mycoplasma, Brucella, Leptospira, Chlamydia; doenças transmitidas por carrapato','Cães/Gatos: 5–10 mg/kg a cada 12–24h VO; Aves: 25–50 mg/kg a cada 24h VO','Gestação, lactação, filhotes jovens (manchas dentárias); administrar com alimento','Fotossensibilização, vômito, erosão esofágica (dar com bastante água)','Oral, IV','A cada 12–24h',5,10),
('Oxitetraciclina','Oxitetraciclina','Antibiótico - Tetraciclina','Bovinos, Equinos, Aves, Suínos, Cães, Gatos','Amplo espectro; pneumonia, mastite, metrite, infecções por Rickettsias','Bovinos/Equinos: 6,6–11 mg/kg IM/IV a cada 24–48h; Cães/Gatos: 7–11 mg/kg a cada 8–12h VO/IM','Gestação, filhotes, insuficiência renal','Irritação tecidual (IM), vômito, diarreia, nefrotoxicidade','Oral, IM, IV','A cada 24–48h',7,11),
('Minociclina','Minociclina cloridrato','Antibiótico - Tetraciclina semissintética','Cães, Gatos','Erliquiose, Bartonella, infecções resistentes a outras tetraciclinas','Cães/Gatos: 5–12,5 mg/kg a cada 12h VO','Gestação, filhotes jovens','Vômito, ataxia vestibular, fotossensibilização','Oral','A cada 12h',5,12.5),
-- === ANTIBIÓTICOS - SULFONAMIDAS ===
('Sulfadiazina + Trimetoprima','Sulfadiazina + Trimetoprima','Antibiótico - Sulfonamida potenciada','Cães, Gatos, Equinos, Bovinos, Aves','Amplo espectro: infecções respiratórias, urinárias, de pele, toxoplasmose (felinos)','Cães/Gatos: 15–30 mg/kg a cada 12–24h VO/SC/IV (combinação 5:1); Equinos: 30 mg/kg a cada 12h VO','Insuficiência hepática/renal, keratoconjuntivite seca (cães), gatos Siameses são mais sensíveis','Ceratoconjuntivite seca, discrasias sanguíneas, cristalúria, anemia hemolítica','Oral, SC, IV','A cada 12–24h',15,30),
('Sulfametoxazol + Trimetoprima','Sulfametoxazol + Trimetoprima','Antibiótico - Sulfonamida potenciada','Cães, Gatos, Aves, Répteis','Infecções bacterianas mistas, pneumocistose, nocardiose, infecções urinárias','Cães/Gatos: 15–30 mg/kg a cada 12h VO; Aves: 40–80 mg/kg a cada 12h VO','Insuficiência renal/hepática, desidratação severa','Anemia, leucopenia, cristalúria, ceratoconjuntivite seca','Oral','A cada 12h',15,30),
-- === ANTIBIÓTICOS - MACROLÍDEOS ===
('Azitromicina','Azitromicina dihidratada','Antibiótico - Macrolídeo','Cães, Gatos, Aves','Infecções respiratórias, pele, Bartonella, Mycoplasma, Toxoplasma, Cryptosporidium','Cães: 5–10 mg/kg/dia VO; Gatos: 5 mg/kg a cada 24h VO; Aves: 40–50 mg/kg a cada 24h','Doença hepática grave, arritmias cardíacas','Vômito, diarreia, anorexia, elevação de enzimas hepáticas','Oral','A cada 24h (3–5 dias)  ',5,10),
('Espiramicina','Espiramicina','Antibiótico - Macrolídeo','Cães, Gatos','Infecções respiratórias, toxoplasmose, infecções orais e dentárias','Cães/Gatos: 25–75 mg/kg/dia VO dividida em 1–2 doses','Doença hepática grave','Vômito, diarreia','Oral','A cada 12–24h',25,75),
('Eritromicina','Eritromicina estolato','Antibiótico - Macrolídeo','Cães, Gatos, Aves','Infecções respiratórias por gram-positivos, Campylobacter, Mycoplasma; procinético GI','Cães: 10–20 mg/kg a cada 8h VO; Aves: 60 mg/kg a cada 8h VO','Doença hepática grave, hipersensibilidade a macrolídeos','Vômito, diarreia, anorexia (dose-dependente)','Oral','A cada 8h',10,20),
-- === ANTIBIÓTICOS - OUTROS ===
('Metronidazol','Metronidazol','Antibiótico - Nitroimidazol / Antiprotozoário','Cães, Gatos, Aves, Répteis','Infecções anaeróbias, Giardia, tricomoníase, colite, doença inflamatória intestinal','Cães/Gatos: 10–25 mg/kg a cada 12–24h VO; Giardia: 15–25 mg/kg a cada 12h por 5–7 dias','Insuficiência hepática grave, 1º trimestre de gestação; hepatotóxico em altas doses','Vômito, anorexia, diarreia, neurotoxicidade (ataxia, convulsões) em doses altas','Oral, IV','A cada 12–24h',10,25),
('Cloranfenicol','Cloranfenicol','Antibiótico - Anfenicol','Cães, Gatos, Aves, Répteis','Reserva para infecções resistentes; rickettsias, Salmonella, infecções do SNC','Cães: 40–50 mg/kg a cada 8h VO; Gatos: 12,5–25 mg/kg a cada 12h VO','Gatos: usar com muito cuidado (metabolismo lento); gestação; aplasia medular em humanos (usar luvas)','Supressão medular, anorexia, vômito, diarreia, anemia aplástica (reversível)','Oral, IM, IV','A cada 8–12h',12.5,50),
('Florfenicol','Florfenicol','Antibiótico - Anfenicol','Bovinos, Suínos, Aves, Peixes','Pneumonia bovina, doenças respiratórias suínas, infecções em aquicultura','Bovinos: 20 mg/kg IM (dose única) ou 40 mg/kg SC; Suínos: 15 mg/kg IM a cada 48h','Gestação (uso com cautela), animais reprodutores','Diarreia, redução da ingestão de alimento','IM, SC','A cada 48–72h',15,40),
('Gentamicina','Gentamicina sulfato','Antibiótico - Aminoglicosídeo','Cães, Gatos, Bovinos, Equinos','Infecções graves por gram-negativos (Pseudomonas, E. coli, Klebsiella); septicemia, infecções oculares e otológicas','Cães/Gatos: 6–9 mg/kg/dia IV/IM/SC (dose única diária); oftalmo: colírio 3–4x/dia; ótico: conforme produto','Insuficiência renal, desidratação; não combinar com anestésicos bloqueadores neuromusculares','Nefrotoxicidade, ototoxicidade (dose e duração dependentes)','IV, IM, SC, tópica (ocular, ótica)','A cada 24h',6,9),
('Amicacina','Amicacina sulfato','Antibiótico - Aminoglicosídeo','Cães, Gatos, Equinos, Aves','Infecções graves por gram-negativos resistentes a gentamicina; Pseudomonas, Klebsiella, Proteus','Cães/Gatos: 15–30 mg/kg/dia SC/IV (dose única); Neonatos: 10–15 mg/kg/dia','Insuficiência renal, desidratação','Nefrotoxicidade, ototoxicidade','IV, SC, IM','A cada 24h',15,30),
('Clindamicina','Clindamicina cloridrato','Antibiótico - Lincosamida','Cães, Gatos','Infecções anaeróbias, gram-positivos; pele, ossos, articulações, cavidade oral, Toxoplasma, Neospora','Cães/Gatos: 5–11 mg/kg a cada 12h VO; infecções ósseas: até 25 mg/kg a cada 12h','Hipersensibilidade a lincosamidas; não usar em roedores, coelhos e cavalos (colite fatal)','Vômito, diarreia, esofagite (gatos); administrar com alimento','Oral, IM, IV','A cada 12h',5,25),
('Lincomicina','Lincomicina cloridrato','Antibiótico - Lincosamida','Cães, Gatos, Suínos, Aves','Infecções por gram-positivos e anaeróbios; alternativa à clindamicina','Cães/Gatos: 15–25 mg/kg a cada 12h VO; Suínos: 11 mg/kg IM a cada 24h','Não usar em roedores, coelhos ou equinos (colite fatal)','Vômito, diarreia','Oral, IM','A cada 12h',15,25),
('Rifampicina','Rifampicina','Antibiótico - Rifamicina','Cães, Gatos, Equinos','Actinomicose, nocardiose, infecções por Rhodococcus equi (potros), Brucella','Cães/Gatos: 5–10 mg/kg a cada 12–24h VO (sempre combinada); Equinos/potros: 5 mg/kg a cada 12h VO','Nunca usar em monoterapia (resistência rápida); doença hepática','Hepatotoxicidade, coloração laranja de urina/fezes/secreções, indução de enzimas hepáticas','Oral','A cada 12–24h',5,10),
-- === ANTI-INFLAMATÓRIOS ===
('Meloxicam','Meloxicam','Anti-inflamatório - AINE (COX-2 seletivo)','Cães, Gatos, Equinos, Bovinos, Répteis','Dor e inflamação aguda e crônica; osteoartrite; pós-operatório','Cães: 0,2 mg/kg no 1º dia, depois 0,1 mg/kg/dia VO/SC/IV; Gatos: 0,1–0,3 mg/kg dose única SC; Equinos: 0,6 mg/kg/dia IV/VO','Insuficiência renal/hepática, úlcera GI, gestação (3º trimestre), animais desidratados; gatos: usar com cautela (metabolismo lento)','Úlcera GI, vômito, diarreia, nefrotoxicidade em uso prolongado','Oral, SC, IV','A cada 24h',0.1,0.2),
('Carprofeno','Carprofeno','Anti-inflamatório - AINE (COX-2 preferencial)','Cães, Gatos, Equinos','Dor e inflamação; osteoartrite; pós-operatório; dor aguda','Cães: 2,2 mg/kg a cada 12h ou 4,4 mg/kg/dia VO/SC/IV; Equinos: 0,7 mg/kg a cada 12h IV','Insuficiência hepática/renal, úlcera GI; Labrador/Retriever: idiossincrasia hepática rara','Hepatotoxicidade idiossincrática (cães, raro), vômito, diarreia, úlcera GI','Oral, SC, IV','A cada 12h',2.2,4.4),
('Cetoprofeno','Cetoprofeno','Anti-inflamatório - AINE (COX não seletivo)','Cães, Gatos, Equinos, Bovinos','Dor e inflamação aguda; febre; pós-operatório','Cães/Gatos: 1 mg/kg/dia VO/SC/IM por até 5 dias; Equinos: 2,2 mg/kg/dia IV/IM','Úlcera GI ativa, insuficiência renal/hepática; não usar por mais de 5 dias','Úlcera GI, vômito, diarreia, nefrotoxicidade','Oral, SC, IM, IV','A cada 24h (máx 5 dias)',1,2.2),
('Flunixina Meglumina','Flunixina meglumina','Anti-inflamatório - AINE (COX não seletivo)','Cães, Equinos, Bovinos, Suínos','Dor visceral (cólica equina), febre, inflamação; endotoxemia; choque séptico','Equinos: 1,1 mg/kg IV/IM a cada 12–24h; Bovinos: 2,2 mg/kg IV 1x/dia; Cães: 1 mg/kg IV/IM dose única','Úlcera GI, insuficiência renal/hepática; não usar SC em equinos (necrose tecidual)','Úlcera GI, nefrotoxicidade, trombocitopenia, hemólise','IV, IM','A cada 12–24h',1,2.2),
('Fenilbutazona','Fenilbutazona','Anti-inflamatório - AINE (Pirazolona)','Equinos','Dor musculoesquelética, laminite, osteoartrite em equinos; segunda linha em bovinos','Equinos: 2,2–4,4 mg/kg a cada 12–24h VO/IV; mín. dose efetiva por mín. tempo','Cães e gatos (toxicidade alta); úlcera GI; anemia aplástica (raro); insuficiência renal','Úlcera GI grave, nefrotoxicidade, discrasias sanguíneas, necrose de mucosa oral','Oral, IV','A cada 12–24h',2.2,4.4),
('Grapiprant','Grapiprant','Anti-inflamatório - Antagonista receptor EP4 (não AINE)','Cães','Osteoartrite e dor musculoesquelética crônica; alternativa a NSAIDs tradicionais com menor risco GI/renal','Cães: 2 mg/kg/dia VO (jejum ou com pouca comida)','Não usar em gestação/lactação; não combinado com outros AINEs ou corticosteroides','Vômito, diarreia, anorexia, letargia (menos que AINEs tradicionais)','Oral','A cada 24h',2,2),
('Robenacoxib','Robenacoxib','Anti-inflamatório - AINE (COX-2 altamente seletivo)','Cães, Gatos','Dor e inflamação aguda, pós-cirúrgica e musculoesquelética','Cães: 1 mg/kg/dia VO (máx 12 dias); Gatos: 1–2,4 mg/kg/dia VO (máx 6 dias) ou SC','Úlcera GI ativa, insuficiência renal/hepática grave','Vômito, diarreia, diminuição apetite','Oral, SC','A cada 24h',1,2.4),
-- === ANALGÉSICOS / OPIOIDES ===
('Tramadol','Tramadol cloridrato','Analgésico - Opioide fraco / Inibidor recaptação serotonina-noradrenalina','Cães, Gatos','Dor moderada a intensa; pós-operatório; dor crônica oncológica ou articular','Cães: 2–5 mg/kg a cada 8h VO; Gatos: 1–2 mg/kg a cada 12h VO (metabolismo limitado)','Uso concomitante com IMAO; convulsões; insuficiência renal/hepática','Sedação, vômito, obstipação, midríase (gatos), disforia','Oral','A cada 8–12h',2,5),
('Morfina','Morfina sulfato','Analgésico - Opioide (agonista mu puro)','Cães, Gatos, Equinos','Dor intensa; pré-medicação anestésica; sedação; dor oncológica terminal','Cães: 0,2–1 mg/kg IM/SC a cada 4h; Gatos: 0,05–0,2 mg/kg IM/SC a cada 4–6h; CRI: conforme protocolo','Trauma craniano, insuficiência respiratória, bradicardia; gatos: excitação paradoxal possível','Sedação, vômito, constipação, depressão respiratória, bradicardia','IM, SC, IV (lento), epidural','A cada 4–6h',0.2,1),
('Buprenorfina','Buprenorfina cloridrato','Analgésico - Opioide (agonista parcial mu)','Cães, Gatos','Dor moderada; pós-operatório; alternativa a opioides plenos com menor depressão respiratória','Cães/Gatos: 0,005–0,02 mg/kg IV/IM/SC a cada 6–8h; gatos: administração transmucosa (TMO) 0,02 mg/kg','Hipersensibilidade; animais com dor intensa (menor eficácia que agonistas plenos)','Sedação leve, bradicardia, salivação (TMO em gatos)','IV, IM, SC, transmucosa (gatos)','A cada 6–8h',0.005,0.02),
('Butorfanol','Butorfanol tartarato','Analgésico - Opioide (agonista-antagonista kappa/mu)','Cães, Gatos, Equinos, Aves','Analgesia moderada; pré-medicação; controle de tosse; sedação em aves','Cães/Gatos: 0,1–0,4 mg/kg IV/IM/SC a cada 2–4h; Equinos: 0,02–0,1 mg/kg IV; Aves: 1–4 mg/kg IM/SC','Animais com dor intensa (efeito teto); insuficiência hepática grave','Sedação, ataxia, bradicardia','IV, IM, SC','A cada 2–4h',0.1,0.4),
('Metadona','Metadona cloridrato','Analgésico - Opioide (agonista mu)','Cães, Gatos, Equinos','Dor intensa; pré-medicação anestésica (menos êmeto que morfina); dor crônica refratária','Cães: 0,1–0,5 mg/kg IV/IM a cada 4–6h; Gatos: 0,1–0,3 mg/kg IM/IV a cada 4h','Arritmias cardíacas, insuficiência respiratória','Sedação, bradicardia, vômito (menor que morfina), miose','IV, IM','A cada 4–6h',0.1,0.5),
('Fentanil','Fentanil citrato','Analgésico - Opioide (agonista mu de alta potência)','Cães, Gatos, Equinos','Analgesia intraoperatória; CRI analgésica; patch transdérmico para dor crônica','CRI Cães: 2–5 µg/kg/h IV; Gatos: 1–3 µg/kg/h IV; Patch: 2–5 µg/kg/h (troca 72–96h)','Depressão respiratória, bradiarritmias; reversão com naloxona','Depressão respiratória, bradicardia, rigidez muscular em altas doses','IV (CRI), patch transdérmico','Contínuo (CRI) ou 72–96h (patch)',0.002,0.005),
('Meperidina (Petidina)','Meperidina cloridrato','Analgésico - Opioide (agonista mu)','Cães, Gatos','Analgesia de curta duração; pré-medicação; alternativa à morfina com menor liberação de histamina','Cães/Gatos: 2–5 mg/kg IM/SC (duração: 45–90 min)','Não usar com IMAO; insuficiência renal (acúmulo de normeperidina)','Sedação breve, vasodilatação, vômito menos frequente que morfina','IM, SC','Única (curta duração)',2,5),
('Naloxona','Naloxona cloridrato','Antagonista opioide','Cães, Gatos, Equinos','Reversão de depressão respiratória por opioides; overdose opioide; reversão de sedação opioide','Cães/Gatos: 0,01–0,04 mg/kg IV/IM/SC (repetir conforme necessário a cada 2–3 min)','Nenhuma absoluta em emergência','Dor aguda, excitação, agitação, recorrência de sedação','IV, IM, SC','Conforme necessário',0.01,0.04),
-- === ANESTÉSICOS GERAIS ===
('Propofol','Propofol','Anestésico geral - Agente indutório','Cães, Gatos','Indução anestésica; TIVA (anestesia total intravenosa); sedação em UTI','Cães: 4–6 mg/kg IV (bolus lento); Gatos: 4–8 mg/kg IV; CRI: 0,1–0,6 mg/kg/min','Hiperlipidemia; administrar lentamente para evitar apneia; descarte após 6h de abertura','Apneia (dose-dependente), hipotensão, dor na injeção, Heinz body anemia em gatos com uso prolongado','IV','Bolus ou CRI',4,8),
('Ketamina','Ketamina cloridrato','Anestésico dissociativo - NMDA antagonista','Cães, Gatos, Equinos, Aves, Répteis, Silvestres','Indução e manutenção anestésica (geralmente combinada); analgesia em doses subanestésicas; captura de silvestres','Cães/Gatos: 5–10 mg/kg IM (sedação) ou 1–2 mg/kg IV (indução); Aves/Répteis: 10–50 mg/kg IM','Não usar em animais com hipertensão intracraniana ou ocular; cardiomiopatia hipertrófica felina (isolada)','Salivação, rigidez muscular, alucinações (recuperação), hipertensão, taquicardia, convulsões (altas doses)','IV, IM','Bolus ou CRI',1,10),
('Alfaxalona','Alfaxalona','Anestésico esteroidal - Neuroesteróide','Cães, Gatos','Indução e manutenção anestésica; sedação; recuperação mais rápida e suave que outros agentes','Cães: 1–3 mg/kg IV (indução); Gatos: 2–5 mg/kg IV ou 5–9 mg/kg IM','Hipersensibilidade; usar com cuidado em cardiopatas','Apneia (passageira), hipotensão, excitação na recuperação (gatos)','IV, IM','Bolus ou CRI',1,5),
('Tiletamina + Zolazepam','Tiletamina + Zolazepam','Anestésico dissociativo + Benzodiazepínico','Cães, Gatos, Silvestres','Contenção química de animais selvagens; sedação/anestesia em campo','Cães: 1–4 mg/kg IM; Gatos: 2–4 mg/kg IM; Silvestres: conforme espécie','Cardiopatia grave, insuficiência hepática/renal','Salivação, rigidez muscular, temperatura elevada, recuperação prolongada em gatos','IM','Dose única',2,4),
-- === SEDATIVOS / PRÉ-MEDICAÇÃO ===
('Acepromazina','Acepromazina maleato','Sedativo - Fenotiazínico','Cães, Gatos, Equinos, Bovinos','Pré-medicação anestésica; contenção química; antiemético (baixa dose)','Cães: 0,025–0,1 mg/kg IV/IM/SC (máx 3 mg total); Gatos: 0,025–0,1 mg/kg IM/SC; Equinos: 0,02–0,05 mg/kg IV','Choque, hipovolemia, epilepsia, boxers (síncope vagal); machos inteiros (parafimose)','Hipotensão, bradicardia, parafimose (cavalos e cães machos), hipotermia','IV, IM, SC','Dose única (pré-med)',0.025,0.1),
('Xilazina','Xilazina cloridrato','Sedativo/Analgésico - Alfa-2 agonista','Cães, Gatos, Equinos, Bovinos, Silvestres','Sedação, analgesia visceral, pré-medicação; aborto em bovinos (efeito oxitócico)','Equinos: 0,5–1,1 mg/kg IV ou 1,1 mg/kg IM; Bovinos: 0,05–0,1 mg/kg IM (alta sensibilidade); Cães: 0,5–1,1 mg/kg IV/IM; Gatos: 0,5–1 mg/kg IM','Cardiopatia, hipotensão, bloqueio AV; bovinos gestantes (risco aborto); não usar em hipovolemia','Bradicardia, bloqueio AV 1º grau, hipotensão, vômito (cães/gatos), diurese, hiperglicemia','IV, IM','Dose única',0.5,1.1),
('Medetomidina','Medetomidina cloridrato','Sedativo/Analgésico - Alfa-2 agonista','Cães, Gatos','Sedação e analgesia; pré-medicação anestésica; efeito mais potente e seletivo que xilazina','Cães/Gatos: 0,01–0,04 mg/kg IM/IV (combinada com outros agentes)','Cardiopatia, bradiarritmia, hipotensão; gestação','Bradicardia intensa, hipotensão, vômito, palidez de mucosas','IV, IM','Dose única',0.01,0.04),
('Dexmedetomidina','Dexmedetomidina cloridrato','Sedativo/Analgésico - Alfa-2 agonista (enantiômero ativo)','Cães, Gatos','Sedação, analgesia e pré-medicação; CRI durante cirurgia (poupador anestésico)','Cães/Gatos: 5–20 µg/kg IV/IM (sedação); CRI: 1–3 µg/kg/h IV','Cardiopatia, hipotensão; gestação; bloqueio AV','Bradicardia, hipotensão, vômito, palidez de mucosas, poliúria','IV, IM','Dose única ou CRI',0.005,0.02),
('Diazepam','Diazepam','Benzodiazepínico - Ansiolítico/Anticonvulsivante','Cães, Gatos, Equinos, Aves','Controle de convulsões (status epilepticus); pré-medicação (combinado); relaxamento muscular; ansiolítico','Cães/Gatos: 0,5–1 mg/kg IV (anticonvulsivante); Equinos: 0,05–0,1 mg/kg IV; Aves: 0,5–2 mg/kg IM','Glaucoma de ângulo fechado, insuficiência hepática grave; gatos: hepatotoxicidade oral relatada','Sedação, ataxia, agitação paradoxal (gatos), hepatotoxicidade (gatos, VO), amnésia','IV, IM, retal','Conforme necessário',0.5,1),
('Midazolam','Midazolam cloridrato','Benzodiazepínico - Ansiolítico/Anticonvulsivante','Cães, Gatos, Aves, Répteis','Pré-medicação anestésica; controle de convulsões; sedação (intranasale seguro)','Cães/Gatos: 0,1–0,3 mg/kg IV/IM; intranasal (status epilepticus): 0,2–0,5 mg/kg','Glaucoma, insuficiência hepática grave','Sedação, ataxia, agitação paradoxal','IV, IM, intranasal','Conforme necessário',0.1,0.3),
-- === ANESTÉSICOS LOCAIS ===
('Lidocaína','Lidocaína cloridrato','Anestésico local / Antiarrítmico','Cães, Gatos, Equinos, Bovinos','Bloqueio local/regional; antiarrítmico (ventricular); CRI analgésica; procinético GI','Bloqueio: 2–4 mg/kg SC/perineuralmente; Antiarrítmico Cães: 2 mg/kg IV bolus lento, depois CRI 25–75 µg/kg/min','Não usar soluções com epinefrina em extremidades distais, pênis, orelhas; não usar em gatos IV (toxicidade)','Toxicidade SNC (tremores, convulsões), arritmias, bloqueio neuromuscular','SC, IV, perineural (bloqueio)','Conforme uso',2,4),
('Bupivacaína','Bupivacaína cloridrato','Anestésico local de longa duração','Cães, Gatos, Equinos','Bloqueio regional de longa duração (3–6h); bloqueio epidural; analgesia pleural','Bloqueio: 1–2 mg/kg perineuralmente (máx 2 mg/kg); epidural: 0,5–1 mL/kg (solução 0,5%)','Cardiotoxicidade em caso de injeção IV acidental; não injetar rapidamente; não usar em veias centrais','Cardiotoxicidade se absorção sistêmica, bloqueio motor prolongado','Perineural, epidural, intrapleural','Única (duração: 3–6h)',1,2),
('Mepivacaína','Mepivacaína cloridrato','Anestésico local','Equinos, Cães','Bloqueio regional em equinos (membros, bainhas tendíneas); bloqueio dental em cães','Equinos: 5–10 mL por local de bloqueio (solução 2%); Cães: 1–2 mg/kg perineural','Hipersensibilidade a amidas','Reações alérgicas, toxicidade SNC/cardíaca em superdosagem','Perineural, intra-articular, intratecal (equinos)','Única (duração: 1–2h)',1,2),
-- === CORTICOSTEROIDES ===
('Prednisona','Prednisona','Corticosteroide - Glicocorticoide oral','Cães, Gatos','Anti-inflamatório, imunossupressor; alergias, DAP, DII, linfoma, doenças autoimunes','Anti-inflamatória: 0,5–1 mg/kg/dia VO; imunossupressora: 1–2 mg/kg/dia VO; reduzir gradualmente','Infecção sistêmica não tratada, diabetes descontrolada, gestação; reduzir dose gradualmente para evitar supressão adrenal','PU/PD, polifagia, alopecia, fraqueza muscular, Cushing iatrogênico, úlcera GI','Oral','A cada 24h (ou dias alternados)',0.5,2),
('Prednisolona','Prednisolona','Corticosteroide - Glicocorticoide (forma ativa)','Cães, Gatos','Preferida para gatos (convertem mal a prednisona); anti-inflamatório, imunossupressor','Cães/Gatos: 1–2 mg/kg/dia VO (imunossupressão); 0,5–1 mg/kg/dia (anti-inflamatório)','Infecção sistêmica, diabetes, Cushing preexistente','PU/PD, polifagia, Cushing iatrogênico, imunossupressão','Oral','A cada 24h',1,2),
('Dexametasona','Dexametasona','Corticosteroide - Glicocorticoide de alta potência','Cães, Gatos, Equinos, Bovinos','Choque endotóxico, edema cerebral, reações alérgicas graves, cetose bovina, estimulação do parto','Cães/Gatos: 0,1–0,2 mg/kg IV/IM (anti-inflamatório); choque: 1–2 mg/kg IV (dose única); Bovinos cetose: 10–20 mg IM','Infecção sistêmica, diabetes, laminite (equinos); úlcera GI; supressão adrenal; gestação (induz parto)','PU/PD, imunossupressão, laminite (equinos), úlcera GI, hiperglicemia','IV, IM, SC, oral, oftálmica','Conforme indicação',0.1,0.2),
('Metilprednisolona','Acetato de metilprednisolona / Succinato sódico','Corticosteroide - Glicocorticoide de alta potência','Cães, Gatos','Trauma medular espinhal agudo (MPSS); doenças alérgicas graves; injeção intra-articular (acetato)','MPSS trauma: 30 mg/kg IV nos primeiros 8h, controverso; intra-articular: 20–40 mg/articulação (acetato)','Infecção sistêmica, diabetes, úlcera GI; uso em trauma medular é controverso (avaliar risco-benefício)','Úlcera GI, imunossupressão, hiperglicemia','IV, IM, intra-articular','Conforme protocolo',30,30),
('Triamcinolona','Triancinolona acetonida','Corticosteroide - Glicocorticoide','Cães, Gatos','Reações alérgicas, dermatites, injeções intra-articulares, doenças autoimunes','Cães/Gatos: 0,1–0,2 mg/kg IM (pode durar 2–6 semanas); intra-articular: 1–3 mg/articulação','Diabetes, infecção ativa, gestação; efeito prolongado requer cautela','Imunossupressão, PU/PD, laminite (equinos), atrofia cutânea (uso repetido)','IM, intra-articular, tópica','Conforme indicação',0.1,0.2),
('Budesonida','Budesonida','Corticosteroide - Glicocorticoide (ação local/intestinal)','Cães, Gatos','Doença inflamatória intestinal (DII); enteropatia responsiva a esteroide; efeito sistêmico mínimo','Cães/Gatos: 0,5–3 mg/animal/dia VO (cápsulas)','Infecção sistêmica, diabetes; menos supressão adrenal que prednisona mas não nula','Efeitos sistêmicos menores que prednisona; PU/PD leve possível','Oral','A cada 24h',NULL,NULL),
-- === ANTIFÚNGICOS ===
('Cetoconazol','Cetoconazol','Antifúngico - Imidazol','Cães, Gatos, Equinos','Dermatofitose, Malassezia, candidíase, blastomicose, histoplasmose; inibidor de síntese de cortisol','Cães: 5–10 mg/kg a cada 12h VO com alimento; Gatos: 5–10 mg/kg/dia VO (menor tolerância)','Insuficiência hepática; interações medicamentosas (inibidor CYP450); gatos: hepatotoxicidade','Hepatotoxicidade, vômito, anorexia, alopecia reversível','Oral','A cada 12h',5,10),
('Fluconazol','Fluconazol','Antifúngico - Triazol (fluconazol)','Cães, Gatos','Candidíase, criptococose, dermatofitose sistêmica; boa penetração no SNC','Cães/Gatos: 2,5–5 mg/kg a cada 12–24h VO; criptococose: 5–10 mg/kg/dia','Doença hepática grave; cuidado com interações (inibidor CYP450)','Vômito, diarreia, elevação de enzimas hepáticas (menos que cetoconazol)','Oral','A cada 12–24h',2.5,10),
('Itraconazol','Itraconazol','Antifúngico - Triazol','Cães, Gatos','Aspergilose, esporotricose, dermatofitose, histoplasmose, blastomicose, cromomicose','Cães: 5 mg/kg/dia VO com alimento; pulso: 5 mg/kg/dia por 1 sem/mês; Gatos: 1,5–3 mg/kg/dia','Doença hepática, gestação, hipersensibilidade; monitorar função hepática','Hepatotoxicidade, vômito, anorexia, vasculites de membros (gatos)','Oral','A cada 24h',5,5),
('Voriconazol','Voriconazol','Antifúngico - Triazol 2ª geração','Cães, Gatos, Aves','Aspergilose invasiva, infecções fúngicas resistentes a outros triazóis','Cães: 4 mg/kg a cada 12h VO; Aves: 12–18 mg/kg a cada 12h VO; Gatos: cautela (toxicidade neurológica)','Insuficiência hepática grave; gatos: neurotoxicidade frequente','Neurotoxicidade (gatos), hepatotoxicidade, distúrbios visuais, vômito','Oral, IV','A cada 12h',4,18),
('Griseofulvina','Griseofulvina micronizada','Antifúngico - Ação na divisão celular fúngica','Cães, Gatos','Dermatofitose (Microsporum, Trichophyton); uso prolongado (4–12 semanas)','Cães/Gatos: 25–50 mg/kg/dia VO dividida em 2 doses (com alimento gorduroso para absorção)','Gestação (teratogênica); FIV/FeLV positivos (mielotoxicidade); insuficiência hepática','Teratogenicidade, mielossupressão (gatos FIV+), vômito, diarreia, hepatotoxicidade','Oral','A cada 12h',25,50),
('Terbinafina','Terbinafina cloridrato','Antifúngico - Alilamina','Cães, Gatos','Dermatofitose, Malassezia, onicomicose; ação fungicida (não apenas estática)','Cães/Gatos: 30–40 mg/kg/dia VO; menor: 5–10 mg/kg/dia em algumas fontes','Doença hepática','Vômito, anorexia, elevação enzimas hepáticas','Oral','A cada 24h',5,40),
('Anfotericina B','Anfotericina B deoxicolato','Antifúngico - Macrólido poliênico','Cães, Gatos','Infecções fúngicas sistêmicas graves (criptococose, histoplasmose, blastomicose, aspergilose invasiva)','Cães: 0,25–0,5 mg/kg IV 3x/semana (em solução glicosada); diluição lenta; formulação lipossomal: 1–3 mg/kg','Insuficiência renal (monitorar creatinina); hidratação prévia obrigatória','Nefrotoxicidade (principal), hipocalemia, anemia, febre, tremores durante infusão','IV (infusão lenta)','3x/semana',0.25,0.5),
-- === ANTIPARASITÁRIOS INTERNOS ===
('Ivermectina','Ivermectina','Antiparasitário - Avermectina (macrocíclico)','Cães, Gatos, Bovinos, Equinos, Suínos, Aves, Répteis','Endoparasitas (ascarídeos, ancilóstomos, filarídeos); ectoparasitas (sarnas, miíase); Dirofilaria (microfilaridas)','Cães: 0,006–0,012 mg/kg VO/SC (prevenção de Dirofilaria); sarna demodécica: 0,3–0,6 mg/kg/dia; Bovinos: 0,2 mg/kg SC; Equinos: 0,2 mg/kg VO','Cão Collie e raças afins (mutação MDR1/ABCB1): risco letal mesmo em doses baixas; não usar em gatos nas doses de Dirofilaria equina','Sinais neurológicos (em raças sensíveis MDR1): midríase, ataxia, coma, morte','Oral, SC, tópica (pour-on)','Conforme indicação',0.006,0.6),
('Milbemicina Oxima','Milbemicina oxima','Antiparasitário - Macrocíclico lactona','Cães, Gatos','Dirofilaria (profilaxia), ancilóstomos, ascarídeos, tricocefalos, sarna sarcóptica, demodecia','Cães/Gatos: 0,5 mg/kg VO 1x/mês (prevenção de Dirofilaria); demodecia: 2 mg/kg/dia','Não testar positivos para Dirofilaria antes de iniciar (risco de choque); MDR1 mutação (cuidado)','Vômito, letargia, ataxia (em doses altas ou raças sensíveis)','Oral','Mensal',0.5,2),
('Moxidectina','Moxidectina','Antiparasitário - Macrocíclico lactona','Cães, Gatos, Bovinos, Equinos','Dirofilaria (prevenção), ancilóstomos; injetável de longa ação (bovinos e equinos)','Cães: 0,003 mg/kg VO mensal; implante subcutâneo: 0,17 mg/kg por 6 meses; Equinos: 0,4 mg/kg VO; Bovinos: 0,2 mg/kg SC','MDR1 positivos; Dirofilaria adulto antes de iniciar','Depressão neurológica (raças sensíveis), ataxia','Oral, SC (implante)','Mensal ou semestral (implante)',0.003,0.4),
('Praziquantel','Praziquantel','Antiparasitário - Cestocida e Trematocida','Cães, Gatos, Equinos, Bovinos, Aves, Répteis','Cestodíase (Dipylidium, Taenia, Echinococcus); trematodíase (Paragonimus)','Cães/Gatos: 5–10 mg/kg VO dose única (podem precisar de 2ª dose em 2 semanas)','Hipersensibilidade; não usar em filhotes <4 semanas','Vômito, diarreia, letargia, salivação (raro)','Oral, SC, IM','Dose única (ou 2 doses)',5,10),
('Fenbendazol','Fenbendazol','Antiparasitário - Benzimidazol','Cães, Gatos, Bovinos, Equinos, Aves, Répteis','Ascarídeos, ancilóstomos, tricocefalos, Giardia, Oslerus osleri (cães), Paragonimus; eficácia variável por espécie','Cães/Gatos: 50 mg/kg/dia VO por 3–5 dias; Giardia: 50 mg/kg/dia por 5 dias; Bovinos/Equinos: 5–10 mg/kg VO','Hipersensibilidade; gestação: usar com cautela (principalmente no 1º trimestre)','Geralmente bem tolerado; vômito, diarreia ocasionais; reações de hipersensibilidade a antígenos de parasitas','Oral','A cada 24h por 3–5 dias',50,50),
('Albendazol','Albendazol','Antiparasitário - Benzimidazol de amplo espectro','Cães, Bovinos, Equinos, Ovinos, Caprinos','Ascarídeos, ancilóstomos, tricocefalos, Giardia (off-label cães), teníase, fasciolose (hepática)','Bovinos: 7,5 mg/kg VO dose única; Equinos: 5–10 mg/kg VO; Cães (Giardia): 25 mg/kg a cada 12h por 2 dias','Gestação (teratogênico - especialmente 45 dias antes do parto em bovinos); gatos: não recomendado (mielotoxicidade)','Mielotoxicidade em gatos, teratogenicidade, vômito, diarreia','Oral','Conforme protocolo',7.5,25),
('Pirantel','Pamoato de pirantel','Antiparasitário - Tetra-hidropirimidina','Cães, Gatos, Equinos, Bovinos','Ascarídeos e ancilóstomos; combinado frequentemente com praziquantel e pamoato de pirantel','Cães/Gatos: 5–10 mg/kg VO dose única; Equinos: 6,6 mg/kg VO','Hipersensibilidade; insuficiência hepática grave; não para Dirofilaria','Vômito, diarreia (dose-dependente)','Oral','Dose única',5,10),
('Emodepside + Praziquantel','Emodepside + Praziquantel','Antiparasitário tópico - Spot-on','Gatos','Toxocara cati, Ancylostoma, Dipylidium, Taenia em gatos; formulação tópica spot-on','Gatos >0,5 kg: 1 pipeta conforme peso do animal (aplicação na nuca)','Não usar em gatos <8 semanas ou <0,5 kg; não usar em outros animais','Salivação (se ingerir durante a grooming), eritema local','Tópica (spot-on)','A cada 1–3 meses (conforme produto)',NULL,NULL),
-- === ANTIPARASITÁRIOS EXTERNOS ===
('Fipronil','Fipronil','Antiparasitário externo - Fenilpirazol','Cães, Gatos','Pulgas, carrapatos, piolhos; spray e spot-on; efeito residual 1–3 meses','Cães/Gatos: spot-on 1 pipeta/mês conforme peso; spray: 7,5 mL/kg (spray 0,25%)','Não usar em coelhos, hamsters, gerbilos; evitar contato com olhos e mucosas','Hipersalivação (lambedura do local de aplicação), eritema local, tremores (raro)','Tópica (spot-on, spray)','Mensal',NULL,NULL),
('Imidacloprida','Imidacloprida','Antiparasitário externo - Neonicotinoide','Cães, Gatos','Pulgas (adultos e larvas); otodectes (ouvido) combinada; geralmente combinada com moxidectina','Cães/Gatos: spot-on 1 pipeta/mês conforme peso','Hipersensibilidade; não usar em filhotes <7 semanas; evitar lambedura','Prurido local transitório, eritema, vômito se ingerido','Tópica (spot-on)','Mensal',NULL,NULL),
('Selamectina','Selamectina','Antiparasitário externo/interno - Avermectina semissintética','Cães, Gatos','Pulgas, carrapatos, sarcoptes (cães), Otodectes, prevenção de Dirofilaria, ancilóstomos (gatos)','Cães/Gatos: spot-on mensal conforme peso; aplicar na nuca','Não usar em filhotes <6 semanas; MDR1 mutados (cuidado em altas doses)','Alopecia transitória no local de aplicação, prurido, vômito (raro)','Tópica (spot-on)','Mensal',NULL,NULL),
('Fluralaner','Fluralaner','Antiparasitário externo - Isoxazolina','Cães, Gatos','Pulgas e carrapatos (ação prolongada: 3 meses em cães, 2–3 meses em gatos)','Cães: 25 mg/kg VO dose única a cada 12 semanas; Gatos: 40 mg/kg spot-on a cada 12 semanas','Não usar em filhotes <8 semanas; epilepsia (risco de convulsões); gestação/lactação','Vômito, diarreia, letargia, anorexia; convulsões em predispostos','Oral, tópica (spot-on gatos)','A cada 12 semanas',25,40),
('Afoxolaner','Afoxolaner','Antiparasitário externo - Isoxazolina','Cães','Pulgas e carrapatos; comprimido mastigável (ação: 1 mês)','Cães: 2,5 mg/kg VO dose única mensal','Epilepsia (risco de convulsões); filhotes <8 semanas e <2 kg; gestação/lactação','Vômito, diarreia, letargia; convulsões em predispostos','Oral','Mensal',2.5,2.5),
('Sarolaner','Sarolaner','Antiparasitário externo - Isoxazolina','Cães','Pulgas e carrapatos; comprimido mastigável (ação: 1 mês); também com milbemicina','Cães: 2–4 mg/kg VO mensal','Epilepsia; filhotes <8 semanas; gestação/lactação','Vômito, diarreia, convulsões (predispostos)','Oral','Mensal',2,4),
('Lotilaner','Lotilaner','Antiparasitário externo - Isoxazolina','Cães, Gatos','Pulgas e carrapatos (ação prolongada: 3 meses); comprimido (cães) e spot-on (gatos)','Cães: 20 mg/kg VO a cada 3 meses; Gatos: spot-on a cada 3 meses','Epilepsia; filhotes <8 semanas; gestação/lactação','Vômito, diarreia, letargia; convulsões em predispostos','Oral, tópica (spot-on gatos)','A cada 3 meses',20,20),
-- === CARDIOVASCULARES ===
('Furosemida','Furosemida','Diurético de alça','Cães, Gatos, Equinos','Edema pulmonar, insuficiência cardíaca congestiva, ascite, edema de membros, hipercalcemia','Cães/Gatos: 1–4 mg/kg IV/IM/SC/VO a cada 4–12h (conforme urgência); Equinos: 0,5–1 mg/kg IV/IM','Anúria, desidratação grave, hipocalemia não tratada, hipotensão','Hipocalemia, desidratação, azotemia pré-renal, alcalose metabólica, ototoxicidade (doses altas IV rápido)','IV, IM, SC, oral','A cada 4–12h',1,4),
('Espironolactona','Espironolactona','Diurético poupador de potássio - Antagonista aldosterona','Cães, Gatos','Insuficiência cardíaca congestiva (adjuvante); ascite hepática; hiperaldosteronismo (gatos)','Cães/Gatos: 1–2 mg/kg/dia VO (geralmente combinado com furosemida)','Hiperpotassemia, insuficiência renal grave, hipotensão','Hiperpotassemia, azotemia, letargia','Oral','A cada 24h',1,2),
('Enalapril','Enalapril maleato','IECA - Inibidor da Enzima Conversora de Angiotensina','Cães, Gatos','Insuficiência cardíaca congestiva, doença valvar mitral, cardiomiopatia dilatada, hipertensão, proteinúria renal','Cães: 0,5 mg/kg a cada 12–24h VO; Gatos: 0,25–0,5 mg/kg a cada 12–24h','Hipotensão, hiperaldosteronismo hiperreninêmico, estenose bilateral de artéria renal; monitorar creatinina','Hipotensão, azotemia, hiperpotassemia','Oral','A cada 12–24h',0.5,0.5),
('Benazepril','Benazepril cloridrato','IECA - Inibidor da Enzima Conversora de Angiotensina','Cães, Gatos','Insuficiência cardíaca, hipertensão, nefropatia crônica, proteinúria; preferido em nefropatas','Cães: 0,25–0,5 mg/kg/dia VO; Gatos: 0,25–0,5 mg/kg/dia','Hipotensão, insuficiência renal bilateral (estenose de artéria renal)','Hipotensão, azotemia leve, hiperpotassemia','Oral','A cada 24h',0.25,0.5),
('Amlodipina','Amlodipina besilato','Bloqueador de canal de cálcio','Cães, Gatos','Hipertensão sistêmica; cardiomiopatia hipertrófica felina (controle de frequência); vasoespasmo','Gatos: 0,625–1,25 mg/gato/dia VO; Cães: 0,05–0,1 mg/kg/dia VO','Hipotensão, insuficiência hepática grave','Hipotensão, edema periférico, taquicardia reflexa (cães)','Oral','A cada 24h',0.05,0.1),
('Atenolol','Atenolol','Beta-bloqueador cardioseletivo (β1)','Cães, Gatos','Taquiarritmias supraventriculares, cardiomiopatia hipertrófica felina, hipertireoidismo (controle FC)','Cães: 0,25–1 mg/kg a cada 12–24h VO; Gatos: 6,25–12,5 mg/gato a cada 12–24h VO','Bradicardia, bloqueio AV 2–3º grau, asma/doença broncoespástica, choque cardiogênico','Bradicardia, letargia, broncoespasmo, hipoglicemia','Oral','A cada 12–24h',0.25,1),
('Digoxina','Digoxina','Glicosídeo cardíaco - Inotrópico positivo','Cães, Gatos','Fibrilação atrial (controle de FC), insuficiência cardíaca congestiva; raramente usada atualmente','Cães: 0,005–0,01 mg/kg a cada 12h VO (reduzir em Dobermans); Gatos: 0,007 mg/kg a cada 48h VO','Hipocalemia, hipercalcemia, insuficiência renal, bradicardia; janela terapêutica estreita','Anorexia, vômito, diarreia, arritmias (toxicidade); monitorar nível sérico','Oral','A cada 12–48h',0.005,0.01),
('Pimobendan','Pimobendan','Inodilatador - Inibidor PDE3 / Sensibilizador ao cálcio','Cães','Insuficiência cardíaca por cardiomiopatia dilatada ou doença valvar mitral; retardar início dos sintomas (preclinical)','Cães: 0,25–0,3 mg/kg a cada 12h VO (em jejum)','Estenose aórtica/pulmonar; não usar em gatos (dados limitados); não dar com alimento','Anorexia, letargia, dispneia (raro); eficácia dependente do estado do paciente','Oral','A cada 12h',0.25,0.3),
-- === GASTROPROTETORES / GASTROINTESTINAIS ===
('Omeprazol','Omeprazol','Inibidor da bomba de prótons (IBP)','Cães, Gatos, Equinos','Úlcera gástrica e duodenal, gastrite por AINEs, esofagite de refluxo, síndrome de Zollinger-Ellison','Cães/Gatos: 0,5–1 mg/kg/dia VO em jejum; Equinos: 4 mg/kg/dia VO (pasta)','Uso prolongado sem indicação (suprime acidez protetora); pode interagir com clopidogrel','Raramente sintomático; uso crônico: hipomagnensemia, gastrite de rebote','Oral','A cada 24h',0.5,1),
('Famotidina','Famotidina','Antagonista H2 (antiulceroso)','Cães, Gatos','Úlcera gástrica e duodenal, gastrite, esofagite de refluxo; menos eficaz que IBPs','Cães/Gatos: 0,5–1 mg/kg a cada 12–24h VO/IV/SC','Hipersensibilidade; insuficiência renal (ajustar dose)','Vômito, constipação; raramente arritmias IV','Oral, IV, SC','A cada 12–24h',0.5,1),
('Sucralfato','Sucralfato','Protetor de mucosa gástrica','Cães, Gatos, Equinos','Úlceras gástricas e duodenais; esofagite por refluxo; proteção de mucosa em uso de AINEs ou corticoides','Cães: 0,5–1 g/animal a cada 6–8h VO em jejum; Gatos: 0,25 g a cada 6–8h VO; Equinos: 4–8 g a cada 6–8h','Administrar separado de outros medicamentos (pode reduzir absorção); insuficiência renal crônica','Constipação; pode reduzir absorção de fluoroquinolonas e outros fármacos','Oral','A cada 6–8h',NULL,NULL),
('Metoclopramida','Metoclopramida cloridrato','Procinético / Antiemético - Antagonista dopamina','Cães, Gatos','Náusea, vômito (quimiorreceptor), gastroparesia, refluxo gastroesofágico; usado em quimioterapia','Cães/Gatos: 0,2–0,5 mg/kg a cada 6–8h VO/SC/IV; CRI: 1–2 mg/kg/24h','Obstrução GI mecânica, hemorragia GI, feocromocitoma; não usar em gatos em altas doses (sinais extrapiramidais)','Sinais extrapiramidais (agitação, movimentos involuntários), sedação','Oral, SC, IV (CRI)','A cada 6–8h',0.2,0.5),
('Maropitant','Maropitant citrato','Antiemético - Antagonista NK1 (substância P)','Cães, Gatos','Prevenção e controle de vômito agudo e crônico; cinetose (enjoo de viagem); vômito por quimioterapia','Cães/Gatos: 1 mg/kg SC/IV a cada 24h; cinetose: 8 mg/kg VO 2h antes; uso máx 5 dias SC consecutivos','Hipersensibilidade; filhotes <16 semanas (SC); insuficiência hepática','Dor no local de injeção SC, letargia, anorexia','SC, IV, oral','A cada 24h',1,8),
('Ondansetrona','Ondansetrona cloridrato','Antiemético - Antagonista 5-HT3','Cães, Gatos','Náusea e vômito (especialmente por quimioterapia, uremia, gastroparesia)','Cães/Gatos: 0,1–0,5 mg/kg IV/VO a cada 12h; CRI: 1 mg/kg/h durante quimio','Obstrução intestinal mecânica; prolongamento QT (monitorar ECG)','Constipação, sedação leve, elevação de enzimas hepáticas','IV, oral','A cada 12h',0.1,0.5),
('Misoprostol','Misoprostol','Análogo de prostaglandina E1 - Protetor de mucosa','Cães, Gatos','Prevenção de úlcera por AINEs ou corticoides; Enterite hemorrágica','Cães: 2–5 µg/kg a cada 6–8h VO com alimento; proteção profilática com AINEs','Gestação (abortifaciente); não usar sem confirmação de ausência de gestação','Diarreia, cólica abdominal, vômito (dose-dependente)','Oral','A cada 6–8h',0.002,0.005),
('Loperamida','Loperamida cloridrato','Antidiarreico - Opioide (ação periférica)','Cães','Diarreia secretora aguda e crônica; enterite idiopática (não infecciosa)','Cães: 0,1–0,2 mg/kg a cada 8h VO','Não usar em diarreia infecciosa/invasiva; gatos: evitar (toxicidade); MDR1 mutados: toxicidade neurológica','Constipação, íleo paralítico em doses altas; toxicidade neurológica em raças MDR1','Oral','A cada 8h',0.1,0.2),
-- === ANTICONVULSIVANTES ===
('Fenobarbital','Fenobarbital','Anticonvulsivante - Barbitúrico','Cães, Gatos, Equinos','Epilepsia idiopática, convulsões sintomáticas; sedação (doses altas); controle de status epilepticus','Cães/Gatos: 2,5–3 mg/kg a cada 12h VO (ajustar por nível sérico: 20–40 µg/mL)','Doença hepática, porfíria; não retirar abruptamente (convulsões de rebote)','Hepatotoxicidade (cão, uso crônico), polifagia, PU/PD, ataxia (início do tratamento), pancitopenia (raro)','Oral, IV','A cada 12h',2.5,3),
('Brometo de Potássio','Brometo de potássio','Anticonvulsivante - Sal de bromo','Cães','Epilepsia idiopática (adjuvante ou monoterapia em intolerantes ao fenobarbital); Status epilepticus (IV)','Cães: 20–30 mg/kg/dia VO (monoterapia); adjuvante: 15–30 mg/kg/dia; nível alvo: 1–3 mg/mL','Gatos: NÃO usar (pneumonite eosinofílica); insuficiência renal; dieta com sal variável afeta nível','Polifagia, PU/PD, fraqueza dos membros posteriores, sedação, pancreatite (raro)','Oral','A cada 24h',15,30),
('Levetiracetam','Levetiracetam','Anticonvulsivante - Modulador SV2A','Cães, Gatos','Epilepsia idiopática (adjuvante); status epilepticus (IV); boa tolerância e poucos efeitos adversos','Cães: 20 mg/kg a cada 8h VO; Gatos: 20–30 mg/kg a cada 8h VO; IV: 30–60 mg/kg (status)','Poucos absolutos; insuficiência renal (ajustar dose)','Sedação, ataxia, irritabilidade (raro)','Oral, IV','A cada 8h',20,30),
('Zonisamida','Zonisamida','Anticonvulsivante - Sulfonamida','Cães, Gatos','Epilepsia idiopática (adjuvante ou monoterapia); alternativa quando fenobarbital é mal tolerado','Cães: 3–7 mg/kg a cada 12h VO; Gatos: 5–10 mg/kg a cada 24h VO','Hipersensibilidade a sulfonamidas; insuficiência renal/hepática','Sedação, ataxia, anorexia, vômito (início), discrasias sanguíneas (raro)','Oral','A cada 12–24h',3,10),
('Gabapentina','Gabapentina','Anticonvulsivante / Analgésico neuropático','Cães, Gatos','Dor neuropática crônica, dor musculoesquelética; convulsões (adjuvante); ansiedade situacional (gatos)','Cães: 5–10 mg/kg a cada 8–12h VO (dor); Gatos: 5–10 mg/kg a cada 12h VO; pré-cirurgia: 10 mg/kg 2h antes','Doença renal (ajustar); não retirar abruptamente','Sedação, ataxia, fraqueza (dose-dependente)','Oral','A cada 8–12h',5,10),
('Pregabalina','Pregabalina','Anticonvulsivante / Analgésico neuropático','Cães, Gatos','Dor neuropática, fibromialgia, epilepsia (adjuvante); maior potência que gabapentina','Cães: 2–4 mg/kg a cada 8–12h VO; Gatos: 1–2 mg/kg a cada 12h VO','Insuficiência renal (ajustar); não retirar abruptamente','Sedação, ataxia, ganho de peso','Oral','A cada 8–12h',2,4),
-- === HORMONAIS / REPRODUÇÃO ===
('Ocitocina','Ocitocina','Hormônio uterino - Ocitócico','Cães, Gatos, Bovinos, Equinos, Suínos','Estimulação das contrações uterinas (distocia por inércia uterina primária), liberação de placenta retida, estimulação da lactação','Cães/Gatos: 2–5 UI IM/SC (pode repetir 20–30 min); Bovinos: 20–40 UI IM/IV; Equinos: 10–20 UI IM','Obstrução mecânica do canal de parto, feto não viável, posição fetal anormal; múltiplas doses seguidas (risco de ruptura)','Espasmo uterino, ansiedade, tenesmo','IM, IV, SC','Conforme necessário',NULL,NULL),
('Aglepristona','Aglepristona','Antiprogestágeno - Bloqueador de receptores de progesterona','Cães, Gatos','Piometra (junto com misoprostol), gestação indesejada (até 45 dias), indução do parto','Piometra: 10 mg/kg SC dias 1, 2 e 7 (ou 14); gestação indesejada: 10 mg/kg dias 1 e 2','Fêmeas em gestação desejada; insuficiência adrenal; hipersensibilidade','Dor no local de injeção, secreção vulvar, letargia, vômito (raro)','SC','Conforme protocolo',10,10),
('Cloprostenol Sódico','Cloprostenol sódico','Prostaglandina F2α sintética - Luteolítico','Cães, Gatos, Bovinos, Equinos, Suínos','Piometra de cérvix aberta, sincronização estral, indução do parto, reabsorção fetal, terapia de corpo lúteo persistente','Cães: 1–3 µg/kg SC a cada 12–24h (piometra, junto com aglepristona); Bovinos: 500 µg IM (sincronização)','Gestação indesejada não autorizada; asma (broncoconstrição); hipersensibilidade; cardiopatas','Salivação, vômito, diarreia, micção, ataxia (transitórios, 30–60 min pós-aplicação)','SC, IM','Conforme protocolo',0.001,0.003),
('Deslorelina','Acetato de deslorelina','Agonista GnRH - Implante de liberação controlada','Cães, Gatos, Equinos, Furões','Supressão reversível da libido em machos (implante); indução da ovulação em éguas; manejo reprodutivo','Cães machos: 4,7–9,4 mg implante SC (6–12 meses de supressão); Éguas: 1,8 mg implante','Gestação; furões: usar com cautela (efeitos paradoxais)','Inflamação local, tumescência testicular transitória inicial (cães)','Implante SC','A cada 6–12 meses (implante)',NULL,NULL),
-- === DERMATOLÓGICOS / IMUNOSSUPRESSORES ===
('Ciclosporina','Ciclosporina A (microemulsão)','Imunossupressor - Inibidor calcineurina','Cães, Gatos','Dermatite atópica, pênfigo foliáceo, ceratoconjuntivite seca (tópica), DII, transplante de órgão (off-label)','Cães: 5 mg/kg/dia VO (reduzir para dias alternados após controle); Gatos: 7 mg/kg/dia VO; CCS (tópica): 1 gota bid','Neoplasia (especialmente linfoma); infecção ativa; gestação; ToxoplasmaFeLV/FIV ativos','Vômito, diarreia, hiperplasia gengival, papilomas virais (cães), imunossupressão, nefrotoxicidade','Oral, tópica (ocular)','A cada 24h',5,7),
('Oclacitinib','Oclacitinib maleato','Imunossupressor - Inibidor JAK (JAK1 seletivo)','Cães','Dermatite atópica, prurido alérgico; início de ação rápido (4h)','Cães: 0,4–0,6 mg/kg a cada 12h VO por até 14 dias, depois 1x/dia','Não usar em < 12 meses; infecção ativa; neoplasia; gestação/lactação; não combinar com outros imunossupressores','Vômito, diarreia, anorexia, letargia; neoplasias (uso prolongado a avaliar)','Oral','A cada 12h (início) ou 24h (manutenção)',0.4,0.6),
-- === OUTROS IMPORTANTES ===
('Atropina','Sulfato de atropina','Anticolinérgico - Antagonista muscarínico','Cães, Gatos, Equinos, Bovinos','Bradicardia sinusal, bloqueio AV, intoxicação por organofosforados/carbamatos, antiespasmódico, midríase (oftalmo)','Bradicardia: 0,02–0,04 mg/kg IV/IM/SC; Organofosforado: 0,2–0,5 mg/kg IV/IM (repetir conforme necessário); Pré-anestesia: 0,02–0,04 mg/kg IM/SC','Glaucoma de ângulo fechado (oftalmo); taquicardia pré-existente; íleo paralítico; megaesôfago','Taquicardia, arritmias, midríase, íleo, retenção urinária, sede','IV, IM, SC, tópica (ocular)','Conforme indicação',0.02,0.04),
('Vitamina K1 (Fitonadiona)','Fitonadiona','Vitamina - Antídoto de anticoagulantes','Cães, Gatos, Equinos, Bovinos','Intoxicação por rodenticidas anticoagulantes (raticidas); coagulopatias por deficiência de vitamina K; hepatopatia','Cães/Gatos: 2,5–5 mg/kg SC (dividida em múltiplos locais)/VO a cada 12h por 3–6 semanas','Hipersensibilidade; administrar SC ou VO (não IV rápido - risco de anafilaxia)','Hemossarcoma no local de injeção repetida; anafilaxia (IV)','SC, VO (nunca IV rápido)','A cada 12h',2.5,5),
('Ácido Ursodesoxicólico','Ácido ursodesoxicólico (UDCA)','Hepatoprotetor - Ácido biliar','Cães, Gatos','Colestase, hepatite crônica, cirrose biliar, colelitíase, hepatopatia por esteroides','Cães/Gatos: 10–15 mg/kg/dia VO com alimento','Obstrução biliar completa; icterícia grave; hipersensibilidade','Vômito, diarreia (raros); geralmente bem tolerado','Oral','A cada 24h',10,15),
('Silimarina','Silimarina (extrato de Silybum marianum)','Hepatoprotetor - Flavonolignan','Cães, Gatos','Hepatoproteção; intoxicação por plantas hepatotóxicas (ex: cogumelo Amanita phalloides); hepatopatia crônica','Cães/Gatos: 50–200 mg/animal/dia VO (doses variáveis por formulação); intoxicação: 20–50 mg/kg/dia','Poucos relatados; hipersensibilidade','Raramente diarreia; geralmente bem tolerado','Oral','A cada 24h',NULL,NULL),
('Metformina','Metformina cloridrato','Antidiabético - Biguanida','Cães, Gatos','Diabetes mellitus tipo 2 (off-label cães); síndrome dos ovários policísticos (off-label); sensibilizador de insulina','Cães: 10–30 mg/kg/dia VO dividida em 2 doses (off-label; eficácia limitada)','Insuficiência renal/hepática; hipoglicemia concomitante com insulina','Vômito, diarreia, acidose láctica (raro)','Oral','A cada 12h',10,30),
('Insulina NPH','Insulina isofana (NPH)','Hormônio - Insulina de ação intermediária','Cães, Gatos','Diabetes mellitus insulinodependente; controle glicêmico','Cães: 0,25–0,5 UI/kg SC a cada 12h (início); Gatos: 0,25–0,5 UI/kg SC a cada 12–24h (início com PZI ou glargina preferidas)','Hipoglicemia; monitorar glicemia; não usar em hipoglicemia','Hipoglicemia (principal), lipodistrofia no local de aplicação','SC','A cada 12h (cães)  ',0.25,0.5),
('Alopurinol','Alopurinol','Uricostático - Inibidor xantina oxidase','Cães','Hiperuricemia, urolitíase por urato em Dálmatas/Bulldogs; Leishmaniose (adjuvante)','Cães: 10 mg/kg a cada 12h VO (urolitíase); Leishmaniose: 10–20 mg/kg/dia VO (combinado com alopurinol)','Não usar em animais com folha-de-figo cristalúria (pode piorar); insuficiência renal grave; ajustar dose','Vômito, anorexia, cristais de xantina (paradoxal se dieta hiperproteica)','Oral','A cada 12h',10,20),
('Fenobarbital Sódico IV','Fenobarbital sódico','Anticonvulsivante - Barbitúrico IV','Cães, Gatos','Status epilepticus; convulsões agudas refratárias; sedação em UTI','Cães/Gatos: 2–4 mg/kg IV lento (1–2 mg/kg/min) para status; repetir a cada 20–30 min conforme necessário','Depressão respiratória; hipotensão; não retirar abruptamente','Depressão respiratória, hipotensão, sedação profunda','IV lento','Conforme necessário',2,4),
('Tiamazol','Tiamazol','Antitireoidiano - Inibidor síntese hormonal','Gatos','Hipertireoidismo felino (tireoidite hiperfuncional); controle antes de tireoidectomia ou radioiodo','Gatos: 2,5–5 mg/gato a cada 12h VO ou tópico (auricular: gel transdérmico)','Hipotireoidismo iatrogênico; linfopenia; gatos com hepatopatia grave','Vômito, anorexia, prurido facial, linfopenia, neutropenia, hepatotoxicidade','Oral, tópica (transdérmica auricular)','A cada 12h',NULL,NULL),
('Colchicina','Colchicina','Anti-inflamatório - Inibidor da polimerização de tubulina','Cães','Amiloidose hepática (Shar-pei, Beagle), fibrose hepática, peritonite idiopática','Cães: 0,01–0,03 mg/kg/dia VO','Insuficiência renal/hepática grave; gestação','Vômito, diarreia, mielossupressão (uso prolongado)','Oral','A cada 24h',0.01,0.03),
('Neostigmina','Neostigmina brometo','Anticolinesterásico - Inibidor da AChE','Cães, Gatos, Equinos, Bovinos','Miastenia gravis, íleo paralítico, reversão de relaxantes musculares não despolarizantes, atonia de bexiga','Cães/Gatos: 0,04 mg/kg SC/IM (crise miastênica); Bovinos: 1–2 mg/animal SC (atonia ruminal)','Obstrução mecânica GI ou urinária, bradiarritmia, asma','Hipersalivação, cólicas abdominais, bradicardia, vômito, micção','SC, IM, IV (lento)','Conforme necessidade',0.04,0.04),
('Vitamina B12 (Cianocobalamina)','Cianocobalamina','Vitamina - Cobalamina','Cães, Gatos, Bovinos','Cobalamina deficiência (EPI, DII, síndrome do intestino curto), anemia megaloblástica, neuropatia','Cães: 500–1000 µg SC semanalmente (8 semanas), depois mensal; Gatos: 250 µg SC semanal (8 semanas)','Hipersensibilidade à cobalamina (rara)','Reação alérgica (rara), rubor transitório','SC, IM, oral (suplementação)','Semanal (início) → mensal',NULL,NULL),
('Doxapram','Doxapram cloridrato','Analéptico respiratório - Estimulante do SNC','Cães, Gatos, Neonatos','Depressão respiratória neonatal (parto difícil), estimulação respiratória pós-anestésica','Neonatos: 1–2 gotas sublinguais (solução diluída); Adultos: 1–2 mg/kg IV','Hipertensão, epilepsia, arritmias; não usar como substituto de ventilação mecânica','Taquicardia, hipertensão, convulsões (superdose)','IV, sublingual (neonatos)','Dose única (emergência)',1,2),
('Acetilcisteína','Acetilcisteína','Mucolítico / Antídoto para paracetamol','Cães, Gatos','Intoxicação por paracetamol/acetaminofeno (antídoto); mucolítico em doenças respiratórias','Intoxicação: 140 mg/kg VO/IV (ataque), depois 70 mg/kg a cada 6h por 7 doses; mucolítico: 10 mg/kg a cada 8h IN/VO','Hipersensibilidade; não usar IV sem diluição adequada','Vômito, reações anafiláticas (raro), broncoespasmo (nebulização)','VO, IV (diluído), inalatória','Conforme indicação',70,140)
) AS v(name, active_ingredient, drug_class, species, indications, dosage, contraindications, adverse_effects, route, frequency, dose_min, dose_max)
WHERE NOT EXISTS (
  SELECT 1 FROM public.drug_reference r WHERE lower(r.name) = lower(v.name)
);
